% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Allel spec},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering

\title{Allel spec}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Creation of a union peak list/set with DiffBind:
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Peak filtering
\item
  Sample filtering: Some samples have very low peaks.
\item
  union list
  \url{https://bioconductor.org/packages/release/bioc/html/DiffBind.html}
\end{enumerate}

Currently, peaks are called for each sample individually. Next, you need
to determine which peaks are ``valid'', e.g.~a peak that was called in
at least 10\% of the samples is valid. Note: VALID peaks should first be
assessed separately for DEX and VEHICLE conditions and for the analysis
the union of these lists should be used.

\begin{enumerate}
\def\labelenumi{\arabic{enumi})}
\setcounter{enumi}{3}
\item
  Differential analysis. Usually, in ChIPseq you have an input or IgG
  control and you would use special tools for the differential analysis.
  This design is different and differential analysis can be carried out
  very similar to the corresponding RNAseq data analysis in DEseq or
  edgeR for treatment condition (veh vs.~dex). You can also run
  differential analysis in DiffBind (which calls DeSeq)
\item
  Allele-specific binding: generate allele-specific count matrix and
  perform RasQUAL (R-package)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{requireNamespace}\NormalTok{(}\StringTok{"BiocManager"}\NormalTok{, }\DataTypeTok{quietly =} \OtherTok{TRUE}\NormalTok{))\{}
  \KeywordTok{install.packages}\NormalTok{(}\StringTok{"BiocManager"}\NormalTok{)}
\NormalTok{  BiocManager}\OperatorTok{::}\KeywordTok{install}\NormalTok{(}\DataTypeTok{version =} \StringTok{"3.12"}\NormalTok{)}
\NormalTok{\}}
  
\ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{require}\NormalTok{(DiffBind))}
\NormalTok{  BiocManager}\OperatorTok{::}\KeywordTok{install}\NormalTok{(}\StringTok{"DiffBind"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(DiffBind)  }

\KeywordTok{library}\NormalTok{(GenomicFeatures)}

\ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{require}\NormalTok{(ChIPseeker))}
\NormalTok{  BiocManager}\OperatorTok{::}\KeywordTok{install}\NormalTok{(}\StringTok{"ChIPseeker"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(ChIPseeker) }

\ControlFlowTok{if}\NormalTok{ (}\OperatorTok{!}\KeywordTok{require}\NormalTok{(TxDb.Hsapiens.UCSC.hg19.knownGene))}
\NormalTok{  BiocManager}\OperatorTok{::}\KeywordTok{install}\NormalTok{(}\StringTok{"TxDb.Hsapiens.UCSC.hg19.knownGene"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(TxDb.Hsapiens.UCSC.hg19.knownGene)}

\ControlFlowTok{if}\NormalTok{(}\OperatorTok{!}\KeywordTok{require}\NormalTok{(dplyr))}
  \KeywordTok{install.packages}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

Obtaining the sites significantly differentially bound (DB) between the
dex samples and veh samples can be done in a five-step script:

\begin{quote}
data = dba(sampleSheet=``samplesheeet.csv'') data = dba.count(data) data
= dba.contrast(data, categories=DBA\_TREATMENT) data = dba.analyze(data)
data.DB = dba.report(data)
\end{quote}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Read in sampleSheet
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{wd <-}\StringTok{ "/Users/anastasiia_hry/github/mpip/signe_chip-seq/"}
\KeywordTok{setwd}\NormalTok{(wd)}

\NormalTok{result.dir.fn <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(wd, }\StringTok{"03_result/"}\NormalTok{)}

\NormalTok{sample.sheet.fn <-}\StringTok{ }\KeywordTok{paste0}\NormalTok{(wd, }\StringTok{"01_sample_sheets/chipseq_diffbind_sample_sheet_local.csv"}\NormalTok{)}
\NormalTok{samples <-}\StringTok{ }\KeywordTok{read.csv2}\NormalTok{(sample.sheet.fn, }\DataTypeTok{head =}\NormalTok{ T)[, }\DecValTok{-11}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(samples, }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                        SampleID Tissue Factor Condition Treatment Replicate
## 1 MPI000637_204526230010_R09C01     NA   ATAC       low       veh         1
## 2 MPI002418_204526230008_R01C02     NA   ATAC       low       veh         1
## 3 MPI003787_204526230010_R04C01     NA   ATAC      high       dex         2
## 4 MPI001701_204526230010_R03C01     NA   ATAC      high       veh         1
## 5 MPI003231_204526230010_R12C01     NA   ATAC      high       veh         1
##                                                                                                                             bamReads
## 1  /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/07_filter_CNV/mpg_L18015_7C_veh_S26.cutadapt.sorted.filtered.rmDups.noCNV.bam
## 2 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/07_filter_CNV/mpg_L18015_14D_veh_S33.cutadapt.sorted.filtered.rmDups.noCNV.bam
## 3 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/07_filter_CNV/mpg_L18015_15B_dex_S72.cutadapt.sorted.filtered.rmDups.noCNV.bam
## 4 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/07_filter_CNV/mpg_L18015_14B_veh_S60.cutadapt.sorted.filtered.rmDups.noCNV.bam
## 5 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/07_filter_CNV/mpg_L18015_18D_veh_S62.cutadapt.sorted.filtered.rmDups.noCNV.bam
##                                                                                                                   Peaks
## 1  /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/06_MASC2_callpeak/mpg_L18015_7C_veh_S26_peaks.narrowPeak.filt.gz
## 2 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/06_MASC2_callpeak/mpg_L18015_14D_veh_S33_peaks.narrowPeak.filt.gz
## 3 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/06_MASC2_callpeak/mpg_L18015_15B_dex_S72_peaks.narrowPeak.filt.gz
## 4 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/06_MASC2_callpeak/mpg_L18015_14B_veh_S60_peaks.narrowPeak.filt.gz
## 5 /Users/anastasiia_hry/Documents/MPIP/SIgne/08_peaks/06_MASC2_callpeak/mpg_L18015_18D_veh_S62_peaks.narrowPeak.filt.gz
##   PeakCaller PeakFormat
## 1       macs     narrow
## 2       macs     narrow
## 3       macs     narrow
## 4       macs     narrow
## 5       macs     narrow
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Create and save a DBA object
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.db <-}\StringTok{ }\KeywordTok{dba}\NormalTok{(}\DataTypeTok{sampleSheet =}\NormalTok{ samples)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## MPI000637_204526230010_R09C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002418_204526230008_R01C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003787_204526230010_R04C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001701_204526230010_R03C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003231_204526230010_R12C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004171_204526230008_R03C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002604_204526230008_R09C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI004054_204526230010_R06C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001263_204526230010_R11C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001786_204526230008_R11C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001946_204526230008_R10C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001113_204526230008_R07C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI000972_204526230010_R10C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004100_204526230010_R09C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003331_204526230010_R08C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003520_204526230008_R03C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI000988_204526230010_R05C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004171_204526230008_R03C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003331_204526230010_R08C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001766_204526230008_R12C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003520_204526230008_R03C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI004215_204526230008_R08C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001946_204526230008_R10C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003353_204526230010_R07C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002319_204526230008_R02C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001109_204526230010_R04C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004251_204526230008_R01C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI000708_204526230010_R07C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004251_204526230008_R01C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002802_204526230008_R04C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002095_204526230010_R10C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003162_204526230008_R02C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002468_204526230010_R01C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002658_204526230010_R05C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003472_204526230008_R08C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004054_204526230010_R06C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002613_204526230010_R08C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003231_204526230010_R12C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002533_204526230010_R11C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002802_204526230008_R04C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003934_204526230008_R12C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002418_204526230008_R01C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001109_204526230010_R04C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001786_204526230008_R11C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003934_204526230008_R12C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002383_204526230010_R02C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004215_204526230008_R08C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004246_204526230010_R12C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001113_204526230008_R07C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001547_204526230008_R05C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001667_204526230008_R06C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI000637_204526230010_R09C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001386_204526230008_R11C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002468_204526230010_R01C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002088_204526230010_R01C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003013_204526230010_R06C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI000972_204526230010_R10C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001048_204526230010_R03C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001389_204526230008_R06C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003785_204526230008_R09C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003155_204526230008_R07C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001886_204526230008_R04C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003787_204526230010_R04C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI004246_204526230010_R12C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002852_204526230008_R05C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002613_204526230010_R08C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001389_204526230008_R06C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003155_204526230008_R07C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI000708_204526230010_R07C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003911_204526230008_R10C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001886_204526230008_R04C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003013_204526230010_R06C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002604_204526230008_R09C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI002533_204526230010_R11C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001547_204526230008_R05C02  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI000988_204526230010_R05C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI004100_204526230010_R09C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003472_204526230008_R08C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001386_204526230008_R11C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003911_204526230008_R10C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003162_204526230008_R02C02  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001701_204526230010_R03C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002383_204526230010_R02C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002658_204526230010_R05C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001766_204526230008_R12C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002852_204526230008_R05C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001263_204526230010_R11C01  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI004198_204526230010_R02C01  ATAC low veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI003353_204526230010_R07C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI001667_204526230008_R06C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002319_204526230008_R02C01  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI003785_204526230008_R09C01  ATAC high veh 1 macs
\end{verbatim}

\begin{verbatim}
## MPI001048_204526230010_R03C02  ATAC high dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002095_204526230010_R10C02  ATAC low dex 2 macs
\end{verbatim}

\begin{verbatim}
## MPI002088_204526230010_R01C02  ATAC low veh 1 macs
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.save}\NormalTok{(dba.db, }\DataTypeTok{file =} \StringTok{"Signe_ChIPseq"}\NormalTok{, }\DataTypeTok{dir =}\NormalTok{ result.dir.fn)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/anastasiia_hry/github/mpip/signe_chip-seq/03_result//dba_Signe_ChIPseq.RData"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# load(paste0(result.dir.fn, "dba_Signe_ChIPseq"))}
\NormalTok{dba.db}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 95 Samples, 24124 sites in matrix (44967 total):
##                               ID Factor Condition Treatment Replicate Intervals
## 1  MPI000637_204526230010_R09C01   ATAC       low       veh         1       460
## 2  MPI002418_204526230008_R01C02   ATAC       low       veh         1       354
## 3  MPI003787_204526230010_R04C01   ATAC      high       dex         2      1955
## 4  MPI001701_204526230010_R03C01   ATAC      high       veh         1      9725
## 5  MPI003231_204526230010_R12C01   ATAC      high       veh         1       236
## 6  MPI004171_204526230008_R03C02   ATAC       low       dex         2      2699
## 7  MPI002604_204526230008_R09C02   ATAC       low       dex         2      1290
## 8  MPI004054_204526230010_R06C02   ATAC       low       dex         2      2302
## 9  MPI001263_204526230010_R11C01   ATAC      high       veh         1       413
## 10 MPI001786_204526230008_R11C02   ATAC      high       veh         1       977
## 11 MPI001946_204526230008_R10C01   ATAC      high       veh         1       771
## 12 MPI001113_204526230008_R07C02   ATAC      high       dex         2       204
## 13 MPI000972_204526230010_R10C01   ATAC       low       veh         1       581
## 14 MPI004100_204526230010_R09C02   ATAC       low       dex         2     19759
## 15 MPI003331_204526230010_R08C01   ATAC       low       veh         1      3347
## 16 MPI003520_204526230008_R03C01   ATAC      high       veh         1       192
## 17 MPI000988_204526230010_R05C02   ATAC      high       veh         1      1493
## 18 MPI004171_204526230008_R03C02   ATAC       low       veh         1       346
## 19 MPI003331_204526230010_R08C01   ATAC       low       dex         2      1706
## 20 MPI001766_204526230008_R12C01   ATAC       low       veh         1       136
## 21 MPI003520_204526230008_R03C01   ATAC      high       dex         2      2950
## 22 MPI004215_204526230008_R08C01   ATAC      high       dex         2      2356
## 23 MPI001946_204526230008_R10C01   ATAC      high       dex         2     17256
## 24 MPI003353_204526230010_R07C02   ATAC       low       veh         1      3097
## 25 MPI002319_204526230008_R02C01   ATAC       low       veh         1       496
## 26 MPI001109_204526230010_R04C02   ATAC      high       veh         1      2130
## 27 MPI004251_204526230008_R01C01   ATAC      high       veh         1       410
## 28 MPI000708_204526230010_R07C01   ATAC       low       veh         1       760
## 29 MPI004251_204526230008_R01C01   ATAC      high       dex         2       563
## 30 MPI002802_204526230008_R04C02   ATAC       low       dex         2      1617
## 31 MPI002095_204526230010_R10C02   ATAC       low       veh         1       237
## 32 MPI003162_204526230008_R02C02   ATAC       low       dex         2       787
## 33 MPI002468_204526230010_R01C01   ATAC      high       veh         1       247
## 34 MPI002658_204526230010_R05C01   ATAC       low       dex         2      4977
## 35 MPI003472_204526230008_R08C02   ATAC      high       veh         1       195
## 36 MPI004054_204526230010_R06C02   ATAC       low       veh         1      3423
## 37 MPI002613_204526230010_R08C02   ATAC      high       dex         2       875
## 38 MPI003231_204526230010_R12C01   ATAC      high       dex         2      2073
## 39 MPI002533_204526230010_R11C02   ATAC      high       dex         2      1120
## 40 MPI002802_204526230008_R04C02   ATAC       low       veh         1       838
## 41 MPI003934_204526230008_R12C02   ATAC      high       veh         1       259
## 42 MPI002418_204526230008_R01C02   ATAC       low       dex         2       708
## 43 MPI001109_204526230010_R04C02   ATAC      high       dex         2       620
## 44 MPI001786_204526230008_R11C02   ATAC      high       dex         2       858
## 45 MPI003934_204526230008_R12C02   ATAC      high       dex         2      7158
## 46 MPI002383_204526230010_R02C02   ATAC       low       veh         1       492
## 47 MPI004215_204526230008_R08C01   ATAC      high       veh         1       400
## 48 MPI004246_204526230010_R12C02   ATAC      high       dex         2      1145
## 49 MPI001113_204526230008_R07C02   ATAC      high       veh         1       242
## 50 MPI001547_204526230008_R05C02   ATAC      high       dex         2       253
## 51 MPI001667_204526230008_R06C02   ATAC      high       veh         1       190
## 52 MPI000637_204526230010_R09C01   ATAC       low       dex         2      1141
## 53 MPI001386_204526230008_R11C01   ATAC      high       dex         2       785
## 54 MPI002468_204526230010_R01C01   ATAC      high       dex         2      1601
## 55 MPI002088_204526230010_R01C02   ATAC       low       dex         2      4266
## 56 MPI003013_204526230010_R06C01   ATAC      high       veh         1      2791
## 57 MPI000972_204526230010_R10C01   ATAC       low       dex         2      3099
## 58 MPI001048_204526230010_R03C02   ATAC      high       veh         1      3022
## 59 MPI001389_204526230008_R06C01   ATAC       low       veh         1       635
## 60 MPI003785_204526230008_R09C01   ATAC      high       dex         2      9905
## 61 MPI003155_204526230008_R07C01   ATAC       low       veh         1       922
## 62 MPI001886_204526230008_R04C01   ATAC       low       veh         1      2438
## 63 MPI003787_204526230010_R04C01   ATAC      high       veh         1       178
## 64 MPI004246_204526230010_R12C02   ATAC      high       veh         1       579
## 65 MPI002852_204526230008_R05C01   ATAC       low       veh         1       365
## 66 MPI002613_204526230010_R08C02   ATAC      high       veh         1      4060
## 67 MPI001389_204526230008_R06C01   ATAC       low       dex         2      2622
## 68 MPI003155_204526230008_R07C01   ATAC       low       dex         2      1290
## 69 MPI000708_204526230010_R07C01   ATAC       low       dex         2      1956
## 70 MPI003911_204526230008_R10C02   ATAC       low       veh         1       246
## 71 MPI001886_204526230008_R04C01   ATAC       low       dex         2      5353
## 72 MPI003013_204526230010_R06C01   ATAC      high       dex         2      1467
## 73 MPI002604_204526230008_R09C02   ATAC       low       veh         1       205
## 74 MPI002533_204526230010_R11C02   ATAC      high       veh         1       302
## 75 MPI001547_204526230008_R05C02   ATAC      high       veh         1       142
## 76 MPI000988_204526230010_R05C02   ATAC      high       dex         2      4918
## 77 MPI004100_204526230010_R09C02   ATAC       low       veh         1       598
## 78 MPI003472_204526230008_R08C02   ATAC      high       dex         2       375
## 79 MPI001386_204526230008_R11C01   ATAC      high       veh         1       235
## 80 MPI003911_204526230008_R10C02   ATAC       low       dex         2       470
## 81 MPI003162_204526230008_R02C02   ATAC       low       veh         1       219
## 82 MPI001701_204526230010_R03C01   ATAC      high       dex         2      3480
## 83 MPI002383_204526230010_R02C02   ATAC       low       dex         2       836
## 84 MPI002658_204526230010_R05C01   ATAC       low       veh         1       181
## 85 MPI001766_204526230008_R12C01   ATAC       low       dex         2     11025
## 86 MPI002852_204526230008_R05C01   ATAC       low       dex         2      8121
## 87 MPI001263_204526230010_R11C01   ATAC      high       dex         2      2089
## 88 MPI004198_204526230010_R02C01   ATAC       low       veh         1       181
## 89 MPI003353_204526230010_R07C02   ATAC       low       dex         2     11524
## 90 MPI001667_204526230008_R06C02   ATAC      high       dex         2      5503
## 91 MPI002319_204526230008_R02C01   ATAC       low       dex         2       831
## 92 MPI003785_204526230008_R09C01   ATAC      high       veh         1      6017
## 93 MPI001048_204526230010_R03C02   ATAC      high       dex         2      2068
## 94 MPI002095_204526230010_R10C02   ATAC       low       dex         2     19071
## 95 MPI002088_204526230010_R01C02   ATAC       low       veh         1      3154
\end{verbatim}

This shows how many peaks are in each peakset, as well as total number
of unique peaks after merging overlapping ones (44'967) and the default
binding matrix of 95 samples by the 24'124 sites that overlap in at
least two of the samples.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Peaksets overlap rate
\end{enumerate}

To determine which peaks are ``valid'', we perform overlap peaksets
analysis for each group (dex and veh) separately.

3.1. Dex group

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.overlap}\NormalTok{(dba.db, dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{dex, }\DataTypeTok{mode=}\NormalTok{DBA_OLAP_RATE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 37757 21482 16679 13616 11128  9285  7674  6495  5523  4707  4062  3458
## [13]  3071  2731  2428  2180  1986  1832  1671  1519  1401  1307  1238  1156
## [25]  1085  1016   932   890   838   774   719   683   632   577   541   500
## [37]   459   419   385   343   306   278   242   216   184   139    93
\end{verbatim}

47 consensus peaksets were identified for dex group, 37'757 of which is
the total number of unique sites, 21'482 - the number of unique sites
appearing in at least two peaksets, 16'679 - the number of sites
overlapping in at least three peaksets, etc.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.overlap}\NormalTok{(dba.db, dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{dex }\OperatorTok{&}\StringTok{ }\NormalTok{dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{high, }\DataTypeTok{mode=}\NormalTok{DBA_OLAP_RATE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 24355 11496  7477  5285  3870  2981  2350  1946  1644  1408  1241  1112
## [13]   973   845   747   665   582   496   407   328   263   206   150    99
\end{verbatim}

24 consensus peaksets were identified for dex group, 24'355 of which is
the total number of unique sites, 11'496 - the number of unique sites
appearing in at least two peaksets, 7'477 - the number of sites
overlapping in at least three peaksets, etc.

3.2. Veh group

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.overlap}\NormalTok{(dba.db, dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{veh, }\DataTypeTok{mode=}\NormalTok{DBA_OLAP_RATE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 21486  8772  5760  4118  3039  2287  1716  1346  1047   832   703   576
## [13]   478   426   386   336   307   281   251   224   208   188   180   175
## [25]   163   153   143   139   131   127   124   120   114   111   107   101
## [37]    98    97    93    90    87    80    77    75    72    67    62    53
\end{verbatim}

48 consensus peaksets were identified for dex group, 21'486 of which is
the total number of unique sites, 8'772 - the number of unique sites
appearing in at least two peaksets, 5'760 - the number of sites
overlapping in at least three peaksets, etc.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.overlap}\NormalTok{(dba.db, dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{veh }\OperatorTok{&}\StringTok{ }\NormalTok{dba.db}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{high, }\DataTypeTok{mode=}\NormalTok{DBA_OLAP_RATE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 17310  6567  3583  2090  1219   751   531   397   317   262   212   178
## [13]   157   141   134   121   111   104    96    87    82    77    68    55
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Create separate consensus peaksets for each of the two treatments (veh
  and dex), then take the union of these two peaksets as the overall
  consensus
\end{enumerate}

Requiring that consensus peaks overlap in at least 20\% of the samples
in each group results in 3039 sites for the veh group and 11'128 sites
for the dex group:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.consensus <-}\StringTok{ }\KeywordTok{dba.peakset}\NormalTok{(dba.db, }\DataTypeTok{consensus =} \KeywordTok{c}\NormalTok{(DBA_TREATMENT), }\DataTypeTok{minOverlap =} \FloatTok{0.2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Add consensus: veh
\end{verbatim}

\begin{verbatim}
## Add consensus: dex
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.consensus}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 97 Samples, 24124 sites in matrix (44967 total):
##                               ID Factor Condition Treatment Replicate Intervals
## 1  MPI000637_204526230010_R09C01   ATAC       low       veh         1       460
## 2  MPI002418_204526230008_R01C02   ATAC       low       veh         1       354
## 3  MPI003787_204526230010_R04C01   ATAC      high       dex         2      1955
## 4  MPI001701_204526230010_R03C01   ATAC      high       veh         1      9725
## 5  MPI003231_204526230010_R12C01   ATAC      high       veh         1       236
## 6  MPI004171_204526230008_R03C02   ATAC       low       dex         2      2699
## 7  MPI002604_204526230008_R09C02   ATAC       low       dex         2      1290
## 8  MPI004054_204526230010_R06C02   ATAC       low       dex         2      2302
## 9  MPI001263_204526230010_R11C01   ATAC      high       veh         1       413
## 10 MPI001786_204526230008_R11C02   ATAC      high       veh         1       977
## 11 MPI001946_204526230008_R10C01   ATAC      high       veh         1       771
## 12 MPI001113_204526230008_R07C02   ATAC      high       dex         2       204
## 13 MPI000972_204526230010_R10C01   ATAC       low       veh         1       581
## 14 MPI004100_204526230010_R09C02   ATAC       low       dex         2     19759
## 15 MPI003331_204526230010_R08C01   ATAC       low       veh         1      3347
## 16 MPI003520_204526230008_R03C01   ATAC      high       veh         1       192
## 17 MPI000988_204526230010_R05C02   ATAC      high       veh         1      1493
## 18 MPI004171_204526230008_R03C02   ATAC       low       veh         1       346
## 19 MPI003331_204526230010_R08C01   ATAC       low       dex         2      1706
## 20 MPI001766_204526230008_R12C01   ATAC       low       veh         1       136
## 21 MPI003520_204526230008_R03C01   ATAC      high       dex         2      2950
## 22 MPI004215_204526230008_R08C01   ATAC      high       dex         2      2356
## 23 MPI001946_204526230008_R10C01   ATAC      high       dex         2     17256
## 24 MPI003353_204526230010_R07C02   ATAC       low       veh         1      3097
## 25 MPI002319_204526230008_R02C01   ATAC       low       veh         1       496
## 26 MPI001109_204526230010_R04C02   ATAC      high       veh         1      2130
## 27 MPI004251_204526230008_R01C01   ATAC      high       veh         1       410
## 28 MPI000708_204526230010_R07C01   ATAC       low       veh         1       760
## 29 MPI004251_204526230008_R01C01   ATAC      high       dex         2       563
## 30 MPI002802_204526230008_R04C02   ATAC       low       dex         2      1617
## 31 MPI002095_204526230010_R10C02   ATAC       low       veh         1       237
## 32 MPI003162_204526230008_R02C02   ATAC       low       dex         2       787
## 33 MPI002468_204526230010_R01C01   ATAC      high       veh         1       247
## 34 MPI002658_204526230010_R05C01   ATAC       low       dex         2      4977
## 35 MPI003472_204526230008_R08C02   ATAC      high       veh         1       195
## 36 MPI004054_204526230010_R06C02   ATAC       low       veh         1      3423
## 37 MPI002613_204526230010_R08C02   ATAC      high       dex         2       875
## 38 MPI003231_204526230010_R12C01   ATAC      high       dex         2      2073
## 39 MPI002533_204526230010_R11C02   ATAC      high       dex         2      1120
## 40 MPI002802_204526230008_R04C02   ATAC       low       veh         1       838
## 41 MPI003934_204526230008_R12C02   ATAC      high       veh         1       259
## 42 MPI002418_204526230008_R01C02   ATAC       low       dex         2       708
## 43 MPI001109_204526230010_R04C02   ATAC      high       dex         2       620
## 44 MPI001786_204526230008_R11C02   ATAC      high       dex         2       858
## 45 MPI003934_204526230008_R12C02   ATAC      high       dex         2      7158
## 46 MPI002383_204526230010_R02C02   ATAC       low       veh         1       492
## 47 MPI004215_204526230008_R08C01   ATAC      high       veh         1       400
## 48 MPI004246_204526230010_R12C02   ATAC      high       dex         2      1145
## 49 MPI001113_204526230008_R07C02   ATAC      high       veh         1       242
## 50 MPI001547_204526230008_R05C02   ATAC      high       dex         2       253
## 51 MPI001667_204526230008_R06C02   ATAC      high       veh         1       190
## 52 MPI000637_204526230010_R09C01   ATAC       low       dex         2      1141
## 53 MPI001386_204526230008_R11C01   ATAC      high       dex         2       785
## 54 MPI002468_204526230010_R01C01   ATAC      high       dex         2      1601
## 55 MPI002088_204526230010_R01C02   ATAC       low       dex         2      4266
## 56 MPI003013_204526230010_R06C01   ATAC      high       veh         1      2791
## 57 MPI000972_204526230010_R10C01   ATAC       low       dex         2      3099
## 58 MPI001048_204526230010_R03C02   ATAC      high       veh         1      3022
## 59 MPI001389_204526230008_R06C01   ATAC       low       veh         1       635
## 60 MPI003785_204526230008_R09C01   ATAC      high       dex         2      9905
## 61 MPI003155_204526230008_R07C01   ATAC       low       veh         1       922
## 62 MPI001886_204526230008_R04C01   ATAC       low       veh         1      2438
## 63 MPI003787_204526230010_R04C01   ATAC      high       veh         1       178
## 64 MPI004246_204526230010_R12C02   ATAC      high       veh         1       579
## 65 MPI002852_204526230008_R05C01   ATAC       low       veh         1       365
## 66 MPI002613_204526230010_R08C02   ATAC      high       veh         1      4060
## 67 MPI001389_204526230008_R06C01   ATAC       low       dex         2      2622
## 68 MPI003155_204526230008_R07C01   ATAC       low       dex         2      1290
## 69 MPI000708_204526230010_R07C01   ATAC       low       dex         2      1956
## 70 MPI003911_204526230008_R10C02   ATAC       low       veh         1       246
## 71 MPI001886_204526230008_R04C01   ATAC       low       dex         2      5353
## 72 MPI003013_204526230010_R06C01   ATAC      high       dex         2      1467
## 73 MPI002604_204526230008_R09C02   ATAC       low       veh         1       205
## 74 MPI002533_204526230010_R11C02   ATAC      high       veh         1       302
## 75 MPI001547_204526230008_R05C02   ATAC      high       veh         1       142
## 76 MPI000988_204526230010_R05C02   ATAC      high       dex         2      4918
## 77 MPI004100_204526230010_R09C02   ATAC       low       veh         1       598
## 78 MPI003472_204526230008_R08C02   ATAC      high       dex         2       375
## 79 MPI001386_204526230008_R11C01   ATAC      high       veh         1       235
## 80 MPI003911_204526230008_R10C02   ATAC       low       dex         2       470
## 81 MPI003162_204526230008_R02C02   ATAC       low       veh         1       219
## 82 MPI001701_204526230010_R03C01   ATAC      high       dex         2      3480
## 83 MPI002383_204526230010_R02C02   ATAC       low       dex         2       836
## 84 MPI002658_204526230010_R05C01   ATAC       low       veh         1       181
## 85 MPI001766_204526230008_R12C01   ATAC       low       dex         2     11025
## 86 MPI002852_204526230008_R05C01   ATAC       low       dex         2      8121
## 87 MPI001263_204526230010_R11C01   ATAC      high       dex         2      2089
## 88 MPI004198_204526230010_R02C01   ATAC       low       veh         1       181
## 89 MPI003353_204526230010_R07C02   ATAC       low       dex         2     11524
## 90 MPI001667_204526230008_R06C02   ATAC      high       dex         2      5503
## 91 MPI002319_204526230008_R02C01   ATAC       low       dex         2       831
## 92 MPI003785_204526230008_R09C01   ATAC      high       veh         1      6017
## 93 MPI001048_204526230010_R03C02   ATAC      high       dex         2      2068
## 94 MPI002095_204526230010_R10C02   ATAC       low       dex         2     19071
## 95 MPI002088_204526230010_R01C02   ATAC       low       veh         1      3154
## 96                           veh   ATAC  low-high       veh         1       832
## 97                           dex   ATAC  high-low       dex         2      4707
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotVenn}\NormalTok{(dba.consensus, dba.consensus}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{Consensus)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Merge peakset list
\end{enumerate}

When forming the global binding matrix consensus peaksets, DiffBind
first identifies all unique peaks amongst the relevant peaksets. As part
of this process, it merges overlapping peaks, replacing them with a
single peak representing the narrowest region that covers all peaks that
overlap by at least one base.

Add a consensus peakset (derived from overlapping peaks in peaksets
already present) :

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.consensus.merge <-}\StringTok{ }\KeywordTok{dba.peakset}\NormalTok{(dba.consensus, }\DataTypeTok{peaks =}\NormalTok{ dba.consensus}\OperatorTok{$}\NormalTok{masks}\OperatorTok{$}\NormalTok{Consensus, }\DataTypeTok{minOverlap =} \DecValTok{1}\NormalTok{)}
\NormalTok{dba.consensus.merge }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 98 Samples, 24124 sites in matrix (44967 total):
##                               ID Factor         Condition Treatment Replicate
## 1  MPI000637_204526230010_R09C01   ATAC               low       veh         1
## 2  MPI002418_204526230008_R01C02   ATAC               low       veh         1
## 3  MPI003787_204526230010_R04C01   ATAC              high       dex         2
## 4  MPI001701_204526230010_R03C01   ATAC              high       veh         1
## 5  MPI003231_204526230010_R12C01   ATAC              high       veh         1
## 6  MPI004171_204526230008_R03C02   ATAC               low       dex         2
## 7  MPI002604_204526230008_R09C02   ATAC               low       dex         2
## 8  MPI004054_204526230010_R06C02   ATAC               low       dex         2
## 9  MPI001263_204526230010_R11C01   ATAC              high       veh         1
## 10 MPI001786_204526230008_R11C02   ATAC              high       veh         1
## 11 MPI001946_204526230008_R10C01   ATAC              high       veh         1
## 12 MPI001113_204526230008_R07C02   ATAC              high       dex         2
## 13 MPI000972_204526230010_R10C01   ATAC               low       veh         1
## 14 MPI004100_204526230010_R09C02   ATAC               low       dex         2
## 15 MPI003331_204526230010_R08C01   ATAC               low       veh         1
## 16 MPI003520_204526230008_R03C01   ATAC              high       veh         1
## 17 MPI000988_204526230010_R05C02   ATAC              high       veh         1
## 18 MPI004171_204526230008_R03C02   ATAC               low       veh         1
## 19 MPI003331_204526230010_R08C01   ATAC               low       dex         2
## 20 MPI001766_204526230008_R12C01   ATAC               low       veh         1
## 21 MPI003520_204526230008_R03C01   ATAC              high       dex         2
## 22 MPI004215_204526230008_R08C01   ATAC              high       dex         2
## 23 MPI001946_204526230008_R10C01   ATAC              high       dex         2
## 24 MPI003353_204526230010_R07C02   ATAC               low       veh         1
## 25 MPI002319_204526230008_R02C01   ATAC               low       veh         1
## 26 MPI001109_204526230010_R04C02   ATAC              high       veh         1
## 27 MPI004251_204526230008_R01C01   ATAC              high       veh         1
## 28 MPI000708_204526230010_R07C01   ATAC               low       veh         1
## 29 MPI004251_204526230008_R01C01   ATAC              high       dex         2
## 30 MPI002802_204526230008_R04C02   ATAC               low       dex         2
## 31 MPI002095_204526230010_R10C02   ATAC               low       veh         1
## 32 MPI003162_204526230008_R02C02   ATAC               low       dex         2
## 33 MPI002468_204526230010_R01C01   ATAC              high       veh         1
## 34 MPI002658_204526230010_R05C01   ATAC               low       dex         2
## 35 MPI003472_204526230008_R08C02   ATAC              high       veh         1
## 36 MPI004054_204526230010_R06C02   ATAC               low       veh         1
## 37 MPI002613_204526230010_R08C02   ATAC              high       dex         2
## 38 MPI003231_204526230010_R12C01   ATAC              high       dex         2
## 39 MPI002533_204526230010_R11C02   ATAC              high       dex         2
## 40 MPI002802_204526230008_R04C02   ATAC               low       veh         1
## 41 MPI003934_204526230008_R12C02   ATAC              high       veh         1
## 42 MPI002418_204526230008_R01C02   ATAC               low       dex         2
## 43 MPI001109_204526230010_R04C02   ATAC              high       dex         2
## 44 MPI001786_204526230008_R11C02   ATAC              high       dex         2
## 45 MPI003934_204526230008_R12C02   ATAC              high       dex         2
## 46 MPI002383_204526230010_R02C02   ATAC               low       veh         1
## 47 MPI004215_204526230008_R08C01   ATAC              high       veh         1
## 48 MPI004246_204526230010_R12C02   ATAC              high       dex         2
## 49 MPI001113_204526230008_R07C02   ATAC              high       veh         1
## 50 MPI001547_204526230008_R05C02   ATAC              high       dex         2
## 51 MPI001667_204526230008_R06C02   ATAC              high       veh         1
## 52 MPI000637_204526230010_R09C01   ATAC               low       dex         2
## 53 MPI001386_204526230008_R11C01   ATAC              high       dex         2
## 54 MPI002468_204526230010_R01C01   ATAC              high       dex         2
## 55 MPI002088_204526230010_R01C02   ATAC               low       dex         2
## 56 MPI003013_204526230010_R06C01   ATAC              high       veh         1
## 57 MPI000972_204526230010_R10C01   ATAC               low       dex         2
## 58 MPI001048_204526230010_R03C02   ATAC              high       veh         1
## 59 MPI001389_204526230008_R06C01   ATAC               low       veh         1
## 60 MPI003785_204526230008_R09C01   ATAC              high       dex         2
## 61 MPI003155_204526230008_R07C01   ATAC               low       veh         1
## 62 MPI001886_204526230008_R04C01   ATAC               low       veh         1
## 63 MPI003787_204526230010_R04C01   ATAC              high       veh         1
## 64 MPI004246_204526230010_R12C02   ATAC              high       veh         1
## 65 MPI002852_204526230008_R05C01   ATAC               low       veh         1
## 66 MPI002613_204526230010_R08C02   ATAC              high       veh         1
## 67 MPI001389_204526230008_R06C01   ATAC               low       dex         2
## 68 MPI003155_204526230008_R07C01   ATAC               low       dex         2
## 69 MPI000708_204526230010_R07C01   ATAC               low       dex         2
## 70 MPI003911_204526230008_R10C02   ATAC               low       veh         1
## 71 MPI001886_204526230008_R04C01   ATAC               low       dex         2
## 72 MPI003013_204526230010_R06C01   ATAC              high       dex         2
## 73 MPI002604_204526230008_R09C02   ATAC               low       veh         1
## 74 MPI002533_204526230010_R11C02   ATAC              high       veh         1
## 75 MPI001547_204526230008_R05C02   ATAC              high       veh         1
## 76 MPI000988_204526230010_R05C02   ATAC              high       dex         2
## 77 MPI004100_204526230010_R09C02   ATAC               low       veh         1
## 78 MPI003472_204526230008_R08C02   ATAC              high       dex         2
## 79 MPI001386_204526230008_R11C01   ATAC              high       veh         1
## 80 MPI003911_204526230008_R10C02   ATAC               low       dex         2
## 81 MPI003162_204526230008_R02C02   ATAC               low       veh         1
## 82 MPI001701_204526230010_R03C01   ATAC              high       dex         2
## 83 MPI002383_204526230010_R02C02   ATAC               low       dex         2
## 84 MPI002658_204526230010_R05C01   ATAC               low       veh         1
## 85 MPI001766_204526230008_R12C01   ATAC               low       dex         2
## 86 MPI002852_204526230008_R05C01   ATAC               low       dex         2
## 87 MPI001263_204526230010_R11C01   ATAC              high       dex         2
## 88 MPI004198_204526230010_R02C01   ATAC               low       veh         1
## 89 MPI003353_204526230010_R07C02   ATAC               low       dex         2
## 90 MPI001667_204526230008_R06C02   ATAC              high       dex         2
## 91 MPI002319_204526230008_R02C01   ATAC               low       dex         2
## 92 MPI003785_204526230008_R09C01   ATAC              high       veh         1
## 93 MPI001048_204526230010_R03C02   ATAC              high       dex         2
## 94 MPI002095_204526230010_R10C02   ATAC               low       dex         2
## 95 MPI002088_204526230010_R01C02   ATAC               low       veh         1
## 96                           veh   ATAC          low-high       veh         1
## 97                           dex   ATAC          high-low       dex         2
## 98                       veh-dex   ATAC low-high-high-low   veh-dex       1-2
##    Intervals
## 1        460
## 2        354
## 3       1955
## 4       9725
## 5        236
## 6       2699
## 7       1290
## 8       2302
## 9        413
## 10       977
## 11       771
## 12       204
## 13       581
## 14     19759
## 15      3347
## 16       192
## 17      1493
## 18       346
## 19      1706
## 20       136
## 21      2950
## 22      2356
## 23     17256
## 24      3097
## 25       496
## 26      2130
## 27       410
## 28       760
## 29       563
## 30      1617
## 31       237
## 32       787
## 33       247
## 34      4977
## 35       195
## 36      3423
## 37       875
## 38      2073
## 39      1120
## 40       838
## 41       259
## 42       708
## 43       620
## 44       858
## 45      7158
## 46       492
## 47       400
## 48      1145
## 49       242
## 50       253
## 51       190
## 52      1141
## 53       785
## 54      1601
## 55      4266
## 56      2791
## 57      3099
## 58      3022
## 59       635
## 60      9905
## 61       922
## 62      2438
## 63       178
## 64       579
## 65       365
## 66      4060
## 67      2622
## 68      1290
## 69      1956
## 70       246
## 71      5353
## 72      1467
## 73       205
## 74       302
## 75       142
## 76      4918
## 77       598
## 78       375
## 79       235
## 80       470
## 81       219
## 82      3480
## 83       836
## 84       181
## 85     11025
## 86      8121
## 87      2089
## 88       181
## 89     11524
## 90      5503
## 91       831
## 92      6017
## 93      2068
## 94     19071
## 95      3154
## 96       832
## 97      4707
## 98      4784
\end{verbatim}

Save union peakset :

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n             <-}\StringTok{ }\KeywordTok{length}\NormalTok{(dba.consensus.merge}\OperatorTok{$}\NormalTok{peaks)}
\NormalTok{union.peakset <-}\StringTok{ }\NormalTok{dba.consensus.merge}\OperatorTok{$}\NormalTok{peaks[[n]][,}\DecValTok{1}\OperatorTok{:}\DecValTok{3}\NormalTok{]}

\KeywordTok{write.table}\NormalTok{(union.peakset, }\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(result.dir.fn, }\StringTok{"union_peakset.tsv"}\NormalTok{), }\DataTypeTok{sep =} \StringTok{"}\CharTok{\textbackslash{}t}\StringTok{"}\NormalTok{, }\DataTypeTok{row.names =}\NormalTok{ F, }\DataTypeTok{col.names =}\NormalTok{ F, }\DataTypeTok{quote =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Generate a binding affinity matrix based on read count scores :
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.count.db <-}\StringTok{ }\KeywordTok{dba.count}\NormalTok{(dba.db, }\DataTypeTok{peaks =}\NormalTok{ union.peakset, }\DataTypeTok{bRemoveDuplicates =}\NormalTok{ F, }\DataTypeTok{score =}\NormalTok{ DBA_SCORE_READS)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Computing summits...
\end{verbatim}

\begin{verbatim}
## Re-centering peaks...
\end{verbatim}

\begin{verbatim}
## Reads will be counted as Paired-end.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{save}\NormalTok{(dba.count.db, }\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(result.dir.fn, }\StringTok{"dba_count.Rda"}\NormalTok{))}

\NormalTok{dba.count.norm.db <-}\StringTok{ }\KeywordTok{dba.count}\NormalTok{(dba.db, }\DataTypeTok{peaks =}\NormalTok{ union.peakset, }\DataTypeTok{bRemoveDuplicates =}\NormalTok{ F)  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Computing summits...
\end{verbatim}

\begin{verbatim}
## Re-centering peaks...
\end{verbatim}

\begin{verbatim}
## Reads will be counted as Paired-end.
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Establishing contrast
\end{enumerate}

Next we need to let DiffBind know how we want to group our samples. In
our case we will group based on treatment. We also have to set the
minMembers parameter to 47 since we have 47 samples in dex and 48 in veh
group.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# load(paste0(result.dir.fn, "dba_count.Rda"))}
\NormalTok{dba.contrast <-}\StringTok{ }\KeywordTok{dba.contrast}\NormalTok{(dba.count.db, }\DataTypeTok{categories =} \KeywordTok{c}\NormalTok{(DBA_CONDITION, DBA_TREATMENT), }\DataTypeTok{minMembers =} \DecValTok{47}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Computing results names...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.contrast }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 95 Samples, 4784 sites in matrix:
##                               ID Factor Condition Treatment Replicate     Reads
## 1  MPI000637_204526230010_R09C01   ATAC       low       veh         1   48646.5
## 2  MPI002418_204526230008_R01C02   ATAC       low       veh         1   39876.0
## 3  MPI003787_204526230010_R04C01   ATAC      high       dex         2  122369.5
## 4  MPI001701_204526230010_R03C01   ATAC      high       veh         1  252860.5
## 5  MPI003231_204526230010_R12C01   ATAC      high       veh         1   32347.0
## 6  MPI004171_204526230008_R03C02   ATAC       low       dex         2  173266.5
## 7  MPI002604_204526230008_R09C02   ATAC       low       dex         2   73592.0
## 8  MPI004054_204526230010_R06C02   ATAC       low       dex         2  133546.5
## 9  MPI001263_204526230010_R11C01   ATAC      high       veh         1   25906.5
## 10 MPI001786_204526230008_R11C02   ATAC      high       veh         1   38769.0
## 11 MPI001946_204526230008_R10C01   ATAC      high       veh         1   44678.0
## 12 MPI001113_204526230008_R07C02   ATAC      high       dex         2   26133.0
## 13 MPI000972_204526230010_R10C01   ATAC       low       veh         1   44139.0
## 14 MPI004100_204526230010_R09C02   ATAC       low       dex         2 1093528.0
## 15 MPI003331_204526230010_R08C01   ATAC       low       veh         1  136884.0
## 16 MPI003520_204526230008_R03C01   ATAC      high       veh         1   34792.5
## 17 MPI000988_204526230010_R05C02   ATAC      high       veh         1   97502.5
## 18 MPI004171_204526230008_R03C02   ATAC       low       veh         1   59254.5
## 19 MPI003331_204526230010_R08C01   ATAC       low       dex         2   80213.0
## 20 MPI001766_204526230008_R12C01   ATAC       low       veh         1   29695.5
## 21 MPI003520_204526230008_R03C01   ATAC      high       dex         2  137986.5
## 22 MPI004215_204526230008_R08C01   ATAC      high       dex         2  120145.0
## 23 MPI001946_204526230008_R10C01   ATAC      high       dex         2 1128909.5
## 24 MPI003353_204526230010_R07C02   ATAC       low       veh         1  136983.5
## 25 MPI002319_204526230008_R02C01   ATAC       low       veh         1   50702.5
## 26 MPI001109_204526230010_R04C02   ATAC      high       veh         1   89583.0
## 27 MPI004251_204526230008_R01C01   ATAC      high       veh         1   35730.5
## 28 MPI000708_204526230010_R07C01   ATAC       low       veh         1   33399.5
## 29 MPI004251_204526230008_R01C01   ATAC      high       dex         2   44901.0
## 30 MPI002802_204526230008_R04C02   ATAC       low       dex         2   79331.0
## 31 MPI002095_204526230010_R10C02   ATAC       low       veh         1   32884.0
## 32 MPI003162_204526230008_R02C02   ATAC       low       dex         2   41535.5
## 33 MPI002468_204526230010_R01C01   ATAC      high       veh         1   38420.0
## 34 MPI002658_204526230010_R05C01   ATAC       low       dex         2  315901.5
## 35 MPI003472_204526230008_R08C02   ATAC      high       veh         1   26032.0
## 36 MPI004054_204526230010_R06C02   ATAC       low       veh         1  174999.5
## 37 MPI002613_204526230010_R08C02   ATAC      high       dex         2   80250.5
## 38 MPI003231_204526230010_R12C01   ATAC      high       dex         2   88498.0
## 39 MPI002533_204526230010_R11C02   ATAC      high       dex         2  113871.0
## 40 MPI002802_204526230008_R04C02   ATAC       low       veh         1   52387.5
## 41 MPI003934_204526230008_R12C02   ATAC      high       veh         1   32213.5
## 42 MPI002418_204526230008_R01C02   ATAC       low       dex         2   56650.5
## 43 MPI001109_204526230010_R04C02   ATAC      high       dex         2   45694.0
## 44 MPI001786_204526230008_R11C02   ATAC      high       dex         2   65412.0
## 45 MPI003934_204526230008_R12C02   ATAC      high       dex         2  357234.0
## 46 MPI002383_204526230010_R02C02   ATAC       low       veh         1   38184.5
## 47 MPI004215_204526230008_R08C01   ATAC      high       veh         1   31424.0
## 48 MPI004246_204526230010_R12C02   ATAC      high       dex         2   86453.5
## 49 MPI001113_204526230008_R07C02   ATAC      high       veh         1   36781.5
## 50 MPI001547_204526230008_R05C02   ATAC      high       dex         2   20935.0
## 51 MPI001667_204526230008_R06C02   ATAC      high       veh         1   33561.5
## 52 MPI000637_204526230010_R09C01   ATAC       low       dex         2   84438.0
## 53 MPI001386_204526230008_R11C01   ATAC      high       dex         2   52700.0
## 54 MPI002468_204526230010_R01C01   ATAC      high       dex         2   92503.5
## 55 MPI002088_204526230010_R01C02   ATAC       low       dex         2  178600.5
## 56 MPI003013_204526230010_R06C01   ATAC      high       veh         1  101447.5
## 57 MPI000972_204526230010_R10C01   ATAC       low       dex         2  112234.5
## 58 MPI001048_204526230010_R03C02   ATAC      high       veh         1   95489.5
## 59 MPI001389_204526230008_R06C01   ATAC       low       veh         1   50559.5
## 60 MPI003785_204526230008_R09C01   ATAC      high       dex         2  378592.5
## 61 MPI003155_204526230008_R07C01   ATAC       low       veh         1   41054.5
## 62 MPI001886_204526230008_R04C01   ATAC       low       veh         1   98282.5
## 63 MPI003787_204526230010_R04C01   ATAC      high       veh         1   27634.0
## 64 MPI004246_204526230010_R12C02   ATAC      high       veh         1   49954.0
## 65 MPI002852_204526230008_R05C01   ATAC       low       veh         1   32191.5
## 66 MPI002613_204526230010_R08C02   ATAC      high       veh         1  199912.5
## 67 MPI001389_204526230008_R06C01   ATAC       low       dex         2  157832.0
## 68 MPI003155_204526230008_R07C01   ATAC       low       dex         2   77820.0
## 69 MPI000708_204526230010_R07C01   ATAC       low       dex         2   96744.0
## 70 MPI003911_204526230008_R10C02   ATAC       low       veh         1   18954.5
## 71 MPI001886_204526230008_R04C01   ATAC       low       dex         2  208394.5
## 72 MPI003013_204526230010_R06C01   ATAC      high       dex         2   62343.5
## 73 MPI002604_204526230008_R09C02   ATAC       low       veh         1   25425.5
## 74 MPI002533_204526230010_R11C02   ATAC      high       veh         1   41036.0
## 75 MPI001547_204526230008_R05C02   ATAC      high       veh         1   27024.5
## 76 MPI000988_204526230010_R05C02   ATAC      high       dex         2  200150.0
## 77 MPI004100_204526230010_R09C02   ATAC       low       veh         1   66633.5
## 78 MPI003472_204526230008_R08C02   ATAC      high       dex         2   37347.5
## 79 MPI001386_204526230008_R11C01   ATAC      high       veh         1   35902.5
## 80 MPI003911_204526230008_R10C02   ATAC       low       dex         2   30382.5
## 81 MPI003162_204526230008_R02C02   ATAC       low       veh         1   36747.0
## 82 MPI001701_204526230010_R03C01   ATAC      high       dex         2   95701.5
## 83 MPI002383_204526230010_R02C02   ATAC       low       dex         2   67016.0
## 84 MPI002658_204526230010_R05C01   ATAC       low       veh         1   21971.5
## 85 MPI001766_204526230008_R12C01   ATAC       low       dex         2  343078.0
## 86 MPI002852_204526230008_R05C01   ATAC       low       dex         2  576255.5
## 87 MPI001263_204526230010_R11C01   ATAC      high       dex         2  112898.5
## 88 MPI004198_204526230010_R02C01   ATAC       low       veh         1   19719.5
## 89 MPI003353_204526230010_R07C02   ATAC       low       dex         2  485290.5
## 90 MPI001667_204526230008_R06C02   ATAC      high       dex         2  158705.5
## 91 MPI002319_204526230008_R02C01   ATAC       low       dex         2   56561.0
## 92 MPI003785_204526230008_R09C01   ATAC      high       veh         1  217473.5
## 93 MPI001048_204526230010_R03C02   ATAC      high       dex         2  101095.5
## 94 MPI002095_204526230010_R10C02   ATAC       low       dex         2  809162.0
## 95 MPI002088_204526230010_R01C02   ATAC       low       veh         1  106472.0
##    FRiP
## 1  0.48
## 2  0.41
## 3  0.60
## 4  0.28
## 5  0.38
## 6  0.61
## 7  0.63
## 8  0.65
## 9  0.46
## 10 0.35
## 11 0.41
## 12 0.45
## 13 0.42
## 14 0.38
## 15 0.33
## 16 0.37
## 17 0.35
## 18 0.34
## 19 0.70
## 20 0.35
## 21 0.72
## 22 0.63
## 23 0.51
## 24 0.34
## 25 0.51
## 26 0.32
## 27 0.42
## 28 0.39
## 29 0.41
## 30 0.60
## 31 0.44
## 32 0.51
## 33 0.42
## 34 0.67
## 35 0.47
## 36 0.32
## 37 0.49
## 38 0.65
## 39 0.45
## 40 0.35
## 41 0.39
## 42 0.53
## 43 0.56
## 44 0.55
## 45 0.60
## 46 0.35
## 47 0.48
## 48 0.62
## 49 0.35
## 50 0.57
## 51 0.38
## 52 0.62
## 53 0.59
## 54 0.71
## 55 0.63
## 56 0.35
## 57 0.43
## 58 0.27
## 59 0.44
## 60 0.43
## 61 0.36
## 62 0.37
## 63 0.45
## 64 0.54
## 65 0.47
## 66 0.31
## 67 0.74
## 68 0.67
## 69 0.57
## 70 0.55
## 71 0.48
## 72 0.62
## 73 0.47
## 74 0.30
## 75 0.43
## 76 0.52
## 77 0.39
## 78 0.45
## 79 0.42
## 80 0.57
## 81 0.39
## 82 0.43
## 83 0.46
## 84 0.48
## 85 0.33
## 86 0.64
## 87 0.69
## 88 0.53
## 89 0.52
## 90 0.47
## 91 0.58
## 92 0.29
## 93 0.60
## 94 0.36
## 95 0.33
## 
## Design: [~Condition + Treatment] | 2 Contrasts:
##      Factor Group Samples Group2 Samples2
## 1 Condition   low      47   high       48
## 2 Treatment   dex      47    veh       48
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  Differential analysis :
\end{enumerate}

8.1. Normalization

A windowing approach that identifies deferentially enriched regions
(from csaw package)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# dba.contrast.norm <- dba.normalize(dba.contrast, normalize = DBA_NORM_LIB, library=DBA_LIBSIZE_PEAKREADS, method = DBA_ALL_METHODS)}
\NormalTok{dba.contrast.norm <-}\StringTok{ }\KeywordTok{dba.normalize}\NormalTok{(dba.contrast, }\DataTypeTok{normalize =}\NormalTok{ DBA_NORM_LIB, }\DataTypeTok{background =}\NormalTok{ T, }\DataTypeTok{method =}\NormalTok{ DBA_ALL_METHODS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Generating background bins...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal.norm <-}\StringTok{ }\KeywordTok{dba.analyze}\NormalTok{(dba.contrast.norm, }\DataTypeTok{method =}\NormalTok{ DBA_ALL_METHODS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Applying Blacklist/Greylists...
\end{verbatim}

\begin{verbatim}
## Genome detected: Hsapiens.NCBI.GRCh38
\end{verbatim}

\begin{verbatim}
## Applying blacklist...
\end{verbatim}

\begin{verbatim}
## Removed: 3 of 4784 intervals.
\end{verbatim}

\begin{verbatim}
## No control reads specified, unable to generate greylist.
\end{verbatim}

\begin{verbatim}
## Re-normalizing...
\end{verbatim}

\begin{verbatim}
## Removed 3 (of 4784) consensus peaks.
\end{verbatim}

\begin{verbatim}
## Analyzing...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal.norm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 95 Samples, 4781 sites in matrix (4784 total):
##                               ID Factor Condition Treatment Replicate     Reads
## 1  MPI000637_204526230010_R09C01   ATAC       low       veh         1   48646.5
## 2  MPI002418_204526230008_R01C02   ATAC       low       veh         1   39876.0
## 3  MPI003787_204526230010_R04C01   ATAC      high       dex         2  122369.5
## 4  MPI001701_204526230010_R03C01   ATAC      high       veh         1  252860.5
## 5  MPI003231_204526230010_R12C01   ATAC      high       veh         1   32347.0
## 6  MPI004171_204526230008_R03C02   ATAC       low       dex         2  173266.5
## 7  MPI002604_204526230008_R09C02   ATAC       low       dex         2   73592.0
## 8  MPI004054_204526230010_R06C02   ATAC       low       dex         2  133546.5
## 9  MPI001263_204526230010_R11C01   ATAC      high       veh         1   25906.5
## 10 MPI001786_204526230008_R11C02   ATAC      high       veh         1   38769.0
## 11 MPI001946_204526230008_R10C01   ATAC      high       veh         1   44678.0
## 12 MPI001113_204526230008_R07C02   ATAC      high       dex         2   26133.0
## 13 MPI000972_204526230010_R10C01   ATAC       low       veh         1   44139.0
## 14 MPI004100_204526230010_R09C02   ATAC       low       dex         2 1093528.0
## 15 MPI003331_204526230010_R08C01   ATAC       low       veh         1  136884.0
## 16 MPI003520_204526230008_R03C01   ATAC      high       veh         1   34792.5
## 17 MPI000988_204526230010_R05C02   ATAC      high       veh         1   97502.5
## 18 MPI004171_204526230008_R03C02   ATAC       low       veh         1   59254.5
## 19 MPI003331_204526230010_R08C01   ATAC       low       dex         2   80213.0
## 20 MPI001766_204526230008_R12C01   ATAC       low       veh         1   29695.5
## 21 MPI003520_204526230008_R03C01   ATAC      high       dex         2  137986.5
## 22 MPI004215_204526230008_R08C01   ATAC      high       dex         2  120145.0
## 23 MPI001946_204526230008_R10C01   ATAC      high       dex         2 1128909.5
## 24 MPI003353_204526230010_R07C02   ATAC       low       veh         1  136983.5
## 25 MPI002319_204526230008_R02C01   ATAC       low       veh         1   50702.5
## 26 MPI001109_204526230010_R04C02   ATAC      high       veh         1   89583.0
## 27 MPI004251_204526230008_R01C01   ATAC      high       veh         1   35730.5
## 28 MPI000708_204526230010_R07C01   ATAC       low       veh         1   33399.5
## 29 MPI004251_204526230008_R01C01   ATAC      high       dex         2   44901.0
## 30 MPI002802_204526230008_R04C02   ATAC       low       dex         2   79331.0
## 31 MPI002095_204526230010_R10C02   ATAC       low       veh         1   32884.0
## 32 MPI003162_204526230008_R02C02   ATAC       low       dex         2   41535.5
## 33 MPI002468_204526230010_R01C01   ATAC      high       veh         1   38420.0
## 34 MPI002658_204526230010_R05C01   ATAC       low       dex         2  315901.5
## 35 MPI003472_204526230008_R08C02   ATAC      high       veh         1   26032.0
## 36 MPI004054_204526230010_R06C02   ATAC       low       veh         1  174999.5
## 37 MPI002613_204526230010_R08C02   ATAC      high       dex         2   80250.5
## 38 MPI003231_204526230010_R12C01   ATAC      high       dex         2   88498.0
## 39 MPI002533_204526230010_R11C02   ATAC      high       dex         2  113871.0
## 40 MPI002802_204526230008_R04C02   ATAC       low       veh         1   52387.5
## 41 MPI003934_204526230008_R12C02   ATAC      high       veh         1   32213.5
## 42 MPI002418_204526230008_R01C02   ATAC       low       dex         2   56650.5
## 43 MPI001109_204526230010_R04C02   ATAC      high       dex         2   45694.0
## 44 MPI001786_204526230008_R11C02   ATAC      high       dex         2   65412.0
## 45 MPI003934_204526230008_R12C02   ATAC      high       dex         2  357234.0
## 46 MPI002383_204526230010_R02C02   ATAC       low       veh         1   38184.5
## 47 MPI004215_204526230008_R08C01   ATAC      high       veh         1   31424.0
## 48 MPI004246_204526230010_R12C02   ATAC      high       dex         2   86453.5
## 49 MPI001113_204526230008_R07C02   ATAC      high       veh         1   36781.5
## 50 MPI001547_204526230008_R05C02   ATAC      high       dex         2   20935.0
## 51 MPI001667_204526230008_R06C02   ATAC      high       veh         1   33561.5
## 52 MPI000637_204526230010_R09C01   ATAC       low       dex         2   84438.0
## 53 MPI001386_204526230008_R11C01   ATAC      high       dex         2   52700.0
## 54 MPI002468_204526230010_R01C01   ATAC      high       dex         2   92503.5
## 55 MPI002088_204526230010_R01C02   ATAC       low       dex         2  178600.5
## 56 MPI003013_204526230010_R06C01   ATAC      high       veh         1  101447.5
## 57 MPI000972_204526230010_R10C01   ATAC       low       dex         2  112234.5
## 58 MPI001048_204526230010_R03C02   ATAC      high       veh         1   95489.5
## 59 MPI001389_204526230008_R06C01   ATAC       low       veh         1   50559.5
## 60 MPI003785_204526230008_R09C01   ATAC      high       dex         2  378592.5
## 61 MPI003155_204526230008_R07C01   ATAC       low       veh         1   41054.5
## 62 MPI001886_204526230008_R04C01   ATAC       low       veh         1   98282.5
## 63 MPI003787_204526230010_R04C01   ATAC      high       veh         1   27634.0
## 64 MPI004246_204526230010_R12C02   ATAC      high       veh         1   49954.0
## 65 MPI002852_204526230008_R05C01   ATAC       low       veh         1   32191.5
## 66 MPI002613_204526230010_R08C02   ATAC      high       veh         1  199912.5
## 67 MPI001389_204526230008_R06C01   ATAC       low       dex         2  157832.0
## 68 MPI003155_204526230008_R07C01   ATAC       low       dex         2   77820.0
## 69 MPI000708_204526230010_R07C01   ATAC       low       dex         2   96744.0
## 70 MPI003911_204526230008_R10C02   ATAC       low       veh         1   18954.5
## 71 MPI001886_204526230008_R04C01   ATAC       low       dex         2  208394.5
## 72 MPI003013_204526230010_R06C01   ATAC      high       dex         2   62343.5
## 73 MPI002604_204526230008_R09C02   ATAC       low       veh         1   25425.5
## 74 MPI002533_204526230010_R11C02   ATAC      high       veh         1   41036.0
## 75 MPI001547_204526230008_R05C02   ATAC      high       veh         1   27024.5
## 76 MPI000988_204526230010_R05C02   ATAC      high       dex         2  200150.0
## 77 MPI004100_204526230010_R09C02   ATAC       low       veh         1   66633.5
## 78 MPI003472_204526230008_R08C02   ATAC      high       dex         2   37347.5
## 79 MPI001386_204526230008_R11C01   ATAC      high       veh         1   35902.5
## 80 MPI003911_204526230008_R10C02   ATAC       low       dex         2   30382.5
## 81 MPI003162_204526230008_R02C02   ATAC       low       veh         1   36747.0
## 82 MPI001701_204526230010_R03C01   ATAC      high       dex         2   95701.5
## 83 MPI002383_204526230010_R02C02   ATAC       low       dex         2   67016.0
## 84 MPI002658_204526230010_R05C01   ATAC       low       veh         1   21971.5
## 85 MPI001766_204526230008_R12C01   ATAC       low       dex         2  343078.0
## 86 MPI002852_204526230008_R05C01   ATAC       low       dex         2  576255.5
## 87 MPI001263_204526230010_R11C01   ATAC      high       dex         2  112898.5
## 88 MPI004198_204526230010_R02C01   ATAC       low       veh         1   19719.5
## 89 MPI003353_204526230010_R07C02   ATAC       low       dex         2  485290.5
## 90 MPI001667_204526230008_R06C02   ATAC      high       dex         2  158705.5
## 91 MPI002319_204526230008_R02C01   ATAC       low       dex         2   56561.0
## 92 MPI003785_204526230008_R09C01   ATAC      high       veh         1  217473.5
## 93 MPI001048_204526230010_R03C02   ATAC      high       dex         2  101095.5
## 94 MPI002095_204526230010_R10C02   ATAC       low       dex         2  809162.0
## 95 MPI002088_204526230010_R01C02   ATAC       low       veh         1  106472.0
##    FRiP
## 1  0.48
## 2  0.41
## 3  0.60
## 4  0.28
## 5  0.38
## 6  0.61
## 7  0.63
## 8  0.65
## 9  0.46
## 10 0.35
## 11 0.41
## 12 0.45
## 13 0.42
## 14 0.38
## 15 0.33
## 16 0.37
## 17 0.34
## 18 0.34
## 19 0.70
## 20 0.35
## 21 0.72
## 22 0.63
## 23 0.51
## 24 0.34
## 25 0.50
## 26 0.32
## 27 0.42
## 28 0.39
## 29 0.41
## 30 0.60
## 31 0.44
## 32 0.51
## 33 0.42
## 34 0.67
## 35 0.47
## 36 0.32
## 37 0.49
## 38 0.65
## 39 0.45
## 40 0.35
## 41 0.39
## 42 0.53
## 43 0.56
## 44 0.55
## 45 0.60
## 46 0.34
## 47 0.48
## 48 0.62
## 49 0.35
## 50 0.57
## 51 0.38
## 52 0.62
## 53 0.59
## 54 0.71
## 55 0.63
## 56 0.35
## 57 0.43
## 58 0.27
## 59 0.44
## 60 0.43
## 61 0.36
## 62 0.37
## 63 0.45
## 64 0.53
## 65 0.47
## 66 0.31
## 67 0.74
## 68 0.67
## 69 0.57
## 70 0.55
## 71 0.48
## 72 0.62
## 73 0.47
## 74 0.30
## 75 0.43
## 76 0.52
## 77 0.39
## 78 0.45
## 79 0.42
## 80 0.57
## 81 0.39
## 82 0.43
## 83 0.46
## 84 0.48
## 85 0.33
## 86 0.64
## 87 0.69
## 88 0.53
## 89 0.52
## 90 0.47
## 91 0.58
## 92 0.29
## 93 0.60
## 94 0.36
## 95 0.33
## 
## Design: [~Condition + Treatment] | 2 Contrasts:
##      Factor Group Samples Group2 Samples2 DB.edgeR DB.DESeq2
## 1 Condition   low      47   high       48        1         0
## 2 Treatment   dex      47    veh       48     3285      1809
\end{verbatim}

Result :

FDR = 5\% :

DeSeq : 1809 of the 4781 are identified as being significantly
differentially bound

EdgeR : 3285 of the 4781

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotMA}\NormalTok{(dba.dif.anal.norm, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{bNormalized=}\NormalTok{F)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotMA}\NormalTok{(dba.dif.anal.norm, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotMA}\NormalTok{(dba.dif.anal.norm, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{th =} \FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-19-1.pdf}

8.2. In-built normalization

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal <-}\StringTok{ }\KeywordTok{dba.analyze}\NormalTok{(dba.contrast, }\DataTypeTok{method =}\NormalTok{ DBA_ALL_METHODS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Applying Blacklist/Greylists...
\end{verbatim}

\begin{verbatim}
## Genome detected: Hsapiens.NCBI.GRCh38
\end{verbatim}

\begin{verbatim}
## Applying blacklist...
\end{verbatim}

\begin{verbatim}
## Removed: 3 of 4784 intervals.
\end{verbatim}

\begin{verbatim}
## No control reads specified, unable to generate greylist.
\end{verbatim}

\begin{verbatim}
## Removed 3 (of 4784) consensus peaks.
\end{verbatim}

\begin{verbatim}
## Normalize edgeR with defaults...
\end{verbatim}

\begin{verbatim}
## Normalize DESeq2 with defaults...
\end{verbatim}

\begin{verbatim}
## Analyzing...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 95 Samples, 4781 sites in matrix (4784 total):
##                               ID Factor Condition Treatment Replicate     Reads
## 1  MPI000637_204526230010_R09C01   ATAC       low       veh         1   48646.5
## 2  MPI002418_204526230008_R01C02   ATAC       low       veh         1   39876.0
## 3  MPI003787_204526230010_R04C01   ATAC      high       dex         2  122369.5
## 4  MPI001701_204526230010_R03C01   ATAC      high       veh         1  252860.5
## 5  MPI003231_204526230010_R12C01   ATAC      high       veh         1   32347.0
## 6  MPI004171_204526230008_R03C02   ATAC       low       dex         2  173266.5
## 7  MPI002604_204526230008_R09C02   ATAC       low       dex         2   73592.0
## 8  MPI004054_204526230010_R06C02   ATAC       low       dex         2  133546.5
## 9  MPI001263_204526230010_R11C01   ATAC      high       veh         1   25906.5
## 10 MPI001786_204526230008_R11C02   ATAC      high       veh         1   38769.0
## 11 MPI001946_204526230008_R10C01   ATAC      high       veh         1   44678.0
## 12 MPI001113_204526230008_R07C02   ATAC      high       dex         2   26133.0
## 13 MPI000972_204526230010_R10C01   ATAC       low       veh         1   44139.0
## 14 MPI004100_204526230010_R09C02   ATAC       low       dex         2 1093528.0
## 15 MPI003331_204526230010_R08C01   ATAC       low       veh         1  136884.0
## 16 MPI003520_204526230008_R03C01   ATAC      high       veh         1   34792.5
## 17 MPI000988_204526230010_R05C02   ATAC      high       veh         1   97502.5
## 18 MPI004171_204526230008_R03C02   ATAC       low       veh         1   59254.5
## 19 MPI003331_204526230010_R08C01   ATAC       low       dex         2   80213.0
## 20 MPI001766_204526230008_R12C01   ATAC       low       veh         1   29695.5
## 21 MPI003520_204526230008_R03C01   ATAC      high       dex         2  137986.5
## 22 MPI004215_204526230008_R08C01   ATAC      high       dex         2  120145.0
## 23 MPI001946_204526230008_R10C01   ATAC      high       dex         2 1128909.5
## 24 MPI003353_204526230010_R07C02   ATAC       low       veh         1  136983.5
## 25 MPI002319_204526230008_R02C01   ATAC       low       veh         1   50702.5
## 26 MPI001109_204526230010_R04C02   ATAC      high       veh         1   89583.0
## 27 MPI004251_204526230008_R01C01   ATAC      high       veh         1   35730.5
## 28 MPI000708_204526230010_R07C01   ATAC       low       veh         1   33399.5
## 29 MPI004251_204526230008_R01C01   ATAC      high       dex         2   44901.0
## 30 MPI002802_204526230008_R04C02   ATAC       low       dex         2   79331.0
## 31 MPI002095_204526230010_R10C02   ATAC       low       veh         1   32884.0
## 32 MPI003162_204526230008_R02C02   ATAC       low       dex         2   41535.5
## 33 MPI002468_204526230010_R01C01   ATAC      high       veh         1   38420.0
## 34 MPI002658_204526230010_R05C01   ATAC       low       dex         2  315901.5
## 35 MPI003472_204526230008_R08C02   ATAC      high       veh         1   26032.0
## 36 MPI004054_204526230010_R06C02   ATAC       low       veh         1  174999.5
## 37 MPI002613_204526230010_R08C02   ATAC      high       dex         2   80250.5
## 38 MPI003231_204526230010_R12C01   ATAC      high       dex         2   88498.0
## 39 MPI002533_204526230010_R11C02   ATAC      high       dex         2  113871.0
## 40 MPI002802_204526230008_R04C02   ATAC       low       veh         1   52387.5
## 41 MPI003934_204526230008_R12C02   ATAC      high       veh         1   32213.5
## 42 MPI002418_204526230008_R01C02   ATAC       low       dex         2   56650.5
## 43 MPI001109_204526230010_R04C02   ATAC      high       dex         2   45694.0
## 44 MPI001786_204526230008_R11C02   ATAC      high       dex         2   65412.0
## 45 MPI003934_204526230008_R12C02   ATAC      high       dex         2  357234.0
## 46 MPI002383_204526230010_R02C02   ATAC       low       veh         1   38184.5
## 47 MPI004215_204526230008_R08C01   ATAC      high       veh         1   31424.0
## 48 MPI004246_204526230010_R12C02   ATAC      high       dex         2   86453.5
## 49 MPI001113_204526230008_R07C02   ATAC      high       veh         1   36781.5
## 50 MPI001547_204526230008_R05C02   ATAC      high       dex         2   20935.0
## 51 MPI001667_204526230008_R06C02   ATAC      high       veh         1   33561.5
## 52 MPI000637_204526230010_R09C01   ATAC       low       dex         2   84438.0
## 53 MPI001386_204526230008_R11C01   ATAC      high       dex         2   52700.0
## 54 MPI002468_204526230010_R01C01   ATAC      high       dex         2   92503.5
## 55 MPI002088_204526230010_R01C02   ATAC       low       dex         2  178600.5
## 56 MPI003013_204526230010_R06C01   ATAC      high       veh         1  101447.5
## 57 MPI000972_204526230010_R10C01   ATAC       low       dex         2  112234.5
## 58 MPI001048_204526230010_R03C02   ATAC      high       veh         1   95489.5
## 59 MPI001389_204526230008_R06C01   ATAC       low       veh         1   50559.5
## 60 MPI003785_204526230008_R09C01   ATAC      high       dex         2  378592.5
## 61 MPI003155_204526230008_R07C01   ATAC       low       veh         1   41054.5
## 62 MPI001886_204526230008_R04C01   ATAC       low       veh         1   98282.5
## 63 MPI003787_204526230010_R04C01   ATAC      high       veh         1   27634.0
## 64 MPI004246_204526230010_R12C02   ATAC      high       veh         1   49954.0
## 65 MPI002852_204526230008_R05C01   ATAC       low       veh         1   32191.5
## 66 MPI002613_204526230010_R08C02   ATAC      high       veh         1  199912.5
## 67 MPI001389_204526230008_R06C01   ATAC       low       dex         2  157832.0
## 68 MPI003155_204526230008_R07C01   ATAC       low       dex         2   77820.0
## 69 MPI000708_204526230010_R07C01   ATAC       low       dex         2   96744.0
## 70 MPI003911_204526230008_R10C02   ATAC       low       veh         1   18954.5
## 71 MPI001886_204526230008_R04C01   ATAC       low       dex         2  208394.5
## 72 MPI003013_204526230010_R06C01   ATAC      high       dex         2   62343.5
## 73 MPI002604_204526230008_R09C02   ATAC       low       veh         1   25425.5
## 74 MPI002533_204526230010_R11C02   ATAC      high       veh         1   41036.0
## 75 MPI001547_204526230008_R05C02   ATAC      high       veh         1   27024.5
## 76 MPI000988_204526230010_R05C02   ATAC      high       dex         2  200150.0
## 77 MPI004100_204526230010_R09C02   ATAC       low       veh         1   66633.5
## 78 MPI003472_204526230008_R08C02   ATAC      high       dex         2   37347.5
## 79 MPI001386_204526230008_R11C01   ATAC      high       veh         1   35902.5
## 80 MPI003911_204526230008_R10C02   ATAC       low       dex         2   30382.5
## 81 MPI003162_204526230008_R02C02   ATAC       low       veh         1   36747.0
## 82 MPI001701_204526230010_R03C01   ATAC      high       dex         2   95701.5
## 83 MPI002383_204526230010_R02C02   ATAC       low       dex         2   67016.0
## 84 MPI002658_204526230010_R05C01   ATAC       low       veh         1   21971.5
## 85 MPI001766_204526230008_R12C01   ATAC       low       dex         2  343078.0
## 86 MPI002852_204526230008_R05C01   ATAC       low       dex         2  576255.5
## 87 MPI001263_204526230010_R11C01   ATAC      high       dex         2  112898.5
## 88 MPI004198_204526230010_R02C01   ATAC       low       veh         1   19719.5
## 89 MPI003353_204526230010_R07C02   ATAC       low       dex         2  485290.5
## 90 MPI001667_204526230008_R06C02   ATAC      high       dex         2  158705.5
## 91 MPI002319_204526230008_R02C01   ATAC       low       dex         2   56561.0
## 92 MPI003785_204526230008_R09C01   ATAC      high       veh         1  217473.5
## 93 MPI001048_204526230010_R03C02   ATAC      high       dex         2  101095.5
## 94 MPI002095_204526230010_R10C02   ATAC       low       dex         2  809162.0
## 95 MPI002088_204526230010_R01C02   ATAC       low       veh         1  106472.0
##    FRiP
## 1  0.48
## 2  0.41
## 3  0.60
## 4  0.28
## 5  0.38
## 6  0.61
## 7  0.63
## 8  0.65
## 9  0.46
## 10 0.35
## 11 0.41
## 12 0.45
## 13 0.42
## 14 0.38
## 15 0.33
## 16 0.37
## 17 0.34
## 18 0.34
## 19 0.70
## 20 0.35
## 21 0.72
## 22 0.63
## 23 0.51
## 24 0.34
## 25 0.50
## 26 0.32
## 27 0.42
## 28 0.39
## 29 0.41
## 30 0.60
## 31 0.44
## 32 0.51
## 33 0.42
## 34 0.67
## 35 0.47
## 36 0.32
## 37 0.49
## 38 0.65
## 39 0.45
## 40 0.35
## 41 0.39
## 42 0.53
## 43 0.56
## 44 0.55
## 45 0.60
## 46 0.34
## 47 0.48
## 48 0.62
## 49 0.35
## 50 0.57
## 51 0.38
## 52 0.62
## 53 0.59
## 54 0.71
## 55 0.63
## 56 0.35
## 57 0.43
## 58 0.27
## 59 0.44
## 60 0.43
## 61 0.36
## 62 0.37
## 63 0.45
## 64 0.53
## 65 0.47
## 66 0.31
## 67 0.74
## 68 0.67
## 69 0.57
## 70 0.55
## 71 0.48
## 72 0.62
## 73 0.47
## 74 0.30
## 75 0.43
## 76 0.52
## 77 0.39
## 78 0.45
## 79 0.42
## 80 0.57
## 81 0.39
## 82 0.43
## 83 0.46
## 84 0.48
## 85 0.33
## 86 0.64
## 87 0.69
## 88 0.53
## 89 0.52
## 90 0.47
## 91 0.58
## 92 0.29
## 93 0.60
## 94 0.36
## 95 0.33
## 
## Design: [~Condition + Treatment] | 2 Contrasts:
##      Factor Group Samples Group2 Samples2 DB.edgeR DB.DESeq2
## 1 Condition   low      47   high       48        4         0
## 2 Treatment   dex      47    veh       48     3270      1766
\end{verbatim}

Result :

FDR = 5\% :

DeSeq : 1766 of the 4781 are identified as being significantly
differentially bound

EdgeR : 3270 of the 4781

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotMA}\NormalTok{(dba.dif.anal, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{bNormalized=}\NormalTok{T)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-21-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotMA}\NormalTok{(dba.dif.anal, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{bNormalized =}\NormalTok{ T, }\DataTypeTok{th =} \FloatTok{0.1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal <-}\StringTok{ }\NormalTok{dba.dif.anal.norm}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotVenn}\NormalTok{(dba.dif.anal, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{method =}\NormalTok{ DBA_ALL_METHODS, }\DataTypeTok{main =} \StringTok{"Binding Site Overlaps, FDR = 5%"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-25-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# dba.dif.anal.th.01 <- dba.dif.anal}
\NormalTok{dba.dif.anal}\OperatorTok{$}\NormalTok{config}\OperatorTok{$}\NormalTok{th <-}\StringTok{ }\FloatTok{0.10}
\KeywordTok{dba.plotVenn}\NormalTok{(dba.dif.anal, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{method =}\NormalTok{ DBA_ALL_METHODS, }\DataTypeTok{main =} \StringTok{"Binding Site Overlaps, FDR = 10%"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# dba.dif.anal.overlap <- dba.overlap(dba.dif.anal, mode = DBA_OLAP_PEAKS, }
\CommentTok{#                           contrast = 2, method=dba.dif.anal$config$AnalysisMethod, th = dba.dif.anal$config$th, }
\CommentTok{#                           bUsePval = dba.dif.anal$config$bUsePval, }
\CommentTok{#                           bCorOnly=TRUE, CorMethod="pearson", }
\CommentTok{#                           DataType = dba.dif.anal$config$DataType)}

\NormalTok{dba.dif.anal.deseq <-}\StringTok{ }\NormalTok{dba.dif.anal}\OperatorTok{$}\NormalTok{DESeq2}
\CommentTok{# dba.dif.anal.deseq@assays@data@listData$counts}

\NormalTok{dba.dif.anal.deseq <-}\StringTok{ }\KeywordTok{dba.analyze}\NormalTok{(dba.contrast, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Applying Blacklist/Greylists...
\end{verbatim}

\begin{verbatim}
## Genome detected: Hsapiens.NCBI.GRCh38
\end{verbatim}

\begin{verbatim}
## Applying blacklist...
\end{verbatim}

\begin{verbatim}
## Removed: 3 of 4784 intervals.
\end{verbatim}

\begin{verbatim}
## No control reads specified, unable to generate greylist.
\end{verbatim}

\begin{verbatim}
## Removed 3 (of 4784) consensus peaks.
\end{verbatim}

\begin{verbatim}
## Normalize DESeq2 with defaults...
\end{verbatim}

\begin{verbatim}
## Analyzing...
\end{verbatim}

\begin{verbatim}
## gene-wise dispersion estimates
\end{verbatim}

\begin{verbatim}
## mean-dispersion relationship
\end{verbatim}

\begin{verbatim}
## final dispersion estimates
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dba.dif.anal.deseq}\OperatorTok{$}\NormalTok{config}\OperatorTok{$}\NormalTok{th <-}\StringTok{ }\FloatTok{0.10}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Retrieve the dif bound sites
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dex.report <-}\StringTok{ }\KeywordTok{dba.report}\NormalTok{(dba.dif.anal.deseq, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{th =}\NormalTok{ dba.dif.anal.deseq}\OperatorTok{$}\NormalTok{config}\OperatorTok{$}\NormalTok{th, }
                                                \DataTypeTok{bCounts =}\NormalTok{ T, }\DataTypeTok{bCalled =}\NormalTok{ T) }\CommentTok{# file = paste0(result.dir.fn, "dex_deseq_report.csv"))}
\KeywordTok{write.csv2}\NormalTok{(dex.report, }\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(result.dir.fn, }\StringTok{"dex_deseq_report.csv"}\NormalTok{))}
\NormalTok{dex.report}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## GRanges object with 2035 ranges and 101 metadata columns:
##        seqnames              ranges strand |      Conc  Conc_dex  Conc_veh
##           <Rle>           <IRanges>  <Rle> | <numeric> <numeric> <numeric>
##   4102        8   11545707-11546107      * |      7.41      8.43         0
##   1431       15   31365735-31366135      * |      8.09      9.11         0
##   2274        2   43131375-43131775      * |      7.52      8.54         0
##   3688        6   35727909-35728309      * |      8.42      9.44         0
##   3577        6   12369970-12370370      * |      6.93      7.94         0
##    ...      ...                 ...    ... .       ...       ...       ...
##    449        1 233407099-233407499      * |      0.21      1.23      0.00
##    761       11   59566187-59566587      * |      3.03      1.82      3.67
##   3545        6       392121-392521      * |      2.61      1.31      3.27
##   3124        4   39353607-39354007      * |      0.49      1.36      0.00
##    798       11   68459992-68460392      * |      2.47      1.33      3.09
##             Fold   p-value       FDR MPI003787_204526230010_R04C01
##        <numeric> <numeric> <numeric>                     <numeric>
##   4102      9.43 5.67e-194 2.16e-190                        360.28
##   1431     10.09 4.17e-186 6.92e-183                        688.27
##   2274      9.19 5.44e-186 6.92e-183                        346.74
##   3688      8.83 7.96e-179 7.59e-176                        740.33
##   3577      8.95 1.69e-173 1.29e-170                        306.13
##    ...       ...       ...       ...                           ...
##    449      1.65    0.0532    0.0998                          0.00
##    761     -1.38    0.0532    0.0998                          0.00
##   3545     -1.46    0.0532    0.0998                          7.29
##   3124      1.33    0.0532    0.0998                          0.00
##    798     -1.33    0.0534    0.1000                          0.00
##        MPI004171_204526230008_R03C02 MPI002604_204526230008_R09C02
##                            <numeric>                     <numeric>
##   4102                        397.85                        351.48
##   1431                        589.05                        843.20
##   2274                        352.25                        592.14
##   3688                        822.90                        818.96
##   3577                        194.14                        244.13
##    ...                           ...                           ...
##    449                          0.00                          0.00
##    761                         11.03                          0.00
##   3545                          8.82                          0.00
##   3124                          0.00                          0.00
##    798                          0.00                         12.12
##        MPI004054_204526230010_R06C02 MPI001113_204526230008_R07C02
##                            <numeric>                     <numeric>
##   4102                        408.36                        180.40
##   1431                        729.89                        468.07
##   2274                        462.74                        307.17
##   3688                        747.07                        336.43
##   3577                        282.42                        151.15
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                          8.59                             0
##   3545                          0.00                             0
##   3124                          6.68                             0
##    798                         12.40                             0
##        MPI004100_204526230010_R09C02 MPI003331_204526230010_R08C01
##                            <numeric>                     <numeric>
##   4102                        126.77                        548.03
##   1431                        245.51                        899.09
##   2274                        204.73                        624.28
##   3688                        197.27                       1146.90
##   3577                         78.53                        409.83
##    ...                           ...                           ...
##    449                          3.73                             0
##    761                          7.81                             0
##   3545                         10.60                             0
##   3124                          4.78                             0
##    798                          7.46                             0
##        MPI003520_204526230008_R03C01 MPI004215_204526230008_R08C01
##                            <numeric>                     <numeric>
##   4102                        447.85                        403.00
##   1431                        649.16                        605.57
##   2274                        409.07                        395.58
##   3688                        801.52                        712.68
##   3577                        363.82                        338.31
##    ...                           ...                           ...
##    449                          9.23                           0.0
##    761                          0.00                           0.0
##   3545                          0.00                           0.0
##   3124                         10.16                           5.3
##    798                          0.00                           0.0
##        MPI001946_204526230008_R10C01 MPI004251_204526230008_R01C01
##                            <numeric>                     <numeric>
##   4102                        284.77                        246.88
##   1431                        419.98                        340.53
##   2274                        311.07                        204.32
##   3688                        471.90                        476.74
##   3577                        177.99                        187.29
##    ...                           ...                           ...
##    449                          7.34                             0
##    761                          4.97                             0
##   3545                          1.13                             0
##   3124                          5.19                             0
##    798                          3.72                             0
##        MPI002802_204526230008_R04C02 MPI003162_204526230008_R02C02
##                            <numeric>                     <numeric>
##   4102                        460.97                        380.39
##   1431                        634.43                        613.54
##   2274                        531.64                        435.61
##   3688                        812.72                        776.13
##   3577                        295.53                        242.35
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI002658_204526230010_R05C01 MPI002613_204526230010_R08C02
##                            <numeric>                     <numeric>
##   4102                        485.23                        266.74
##   1431                        732.48                        485.85
##   2274                        539.68                        349.31
##   3688                        812.75                        687.50
##   3577                        229.10                        242.93
##    ...                           ...                           ...
##    449                          7.26                             0
##    761                          0.00                             0
##   3545                          0.00                             0
##   3124                          7.66                             0
##    798                          0.00                             0
##        MPI003231_204526230010_R12C01 MPI002533_204526230010_R11C02
##                            <numeric>                     <numeric>
##   4102                        388.74                        261.84
##   1431                        643.58                        459.90
##   2274                        368.59                        320.03
##   3688                        799.08                        778.80
##   3577                        407.46                        189.11
##    ...                           ...                           ...
##    449                          8.64                             0
##    761                          0.00                             0
##   3545                          0.00                             0
##   3124                          0.00                             0
##    798                          0.00                             0
##        MPI002418_204526230008_R01C02 MPI001109_204526230010_R04C02
##                            <numeric>                     <numeric>
##   4102                        290.15                        404.33
##   1431                        494.82                        680.40
##   2274                        296.89                        479.62
##   3688                        616.28                        839.34
##   3577                        157.44                        317.89
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001786_204526230008_R11C02 MPI003934_204526230008_R12C02
##                            <numeric>                     <numeric>
##   4102                        383.74                        368.45
##   1431                        656.45                        521.47
##   2274                        440.23                        339.56
##   3688                        695.41                        694.81
##   3577                        340.89                        217.93
##    ...                           ...                           ...
##    449                             0                          9.27
##    761                             0                          4.99
##   3545                             0                          0.00
##   3124                             0                          6.06
##    798                             0                          0.00
##        MPI004246_204526230010_R12C02 MPI001547_204526230008_R05C02
##                            <numeric>                     <numeric>
##   4102                        456.89                        383.44
##   1431                        627.85                        748.62
##   2274                        481.94                        450.39
##   3688                        854.82                        906.87
##   3577                        266.76                        353.01
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                         16.21                             0
##   3545                          0.00                             0
##   3124                          0.00                             0
##    798                          0.00                             0
##        MPI000637_204526230010_R09C01 MPI001386_204526230008_R11C01
##                            <numeric>                     <numeric>
##   4102                        452.70                        427.95
##   1431                        872.21                        512.57
##   2274                        520.61                        343.33
##   3688                        932.57                        853.48
##   3577                        307.84                        263.54
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI002468_204526230010_R01C01 MPI002088_204526230010_R01C02
##                            <numeric>                     <numeric>
##   4102                        608.83                        341.02
##   1431                        807.18                        515.81
##   2274                        508.28                        266.82
##   3688                       1141.90                        659.21
##   3577                        422.87                        222.59
##    ...                           ...                           ...
##    449                             0                         18.55
##    761                             0                          0.00
##   3545                             0                          0.00
##   3124                             0                          4.99
##    798                             0                          0.00
##        MPI000972_204526230010_R10C01 MPI003785_204526230008_R09C01
##                            <numeric>                     <numeric>
##   4102                        133.96                        150.44
##   1431                        199.81                        199.24
##   2274                        136.23                        137.99
##   3688                        291.77                        276.31
##   3577                         88.55                        118.13
##    ...                           ...                           ...
##    449                          0.00                         11.11
##    761                          0.00                          0.00
##   3545                          0.00                          4.04
##   3124                         14.76                          3.03
##    798                          0.00                          2.69
##        MPI001389_204526230008_R06C01 MPI003155_204526230008_R07C01
##                            <numeric>                     <numeric>
##   4102                        502.95                        509.21
##   1431                        676.52                        800.66
##   2274                        423.83                        469.92
##   3688                        906.60                       1000.42
##   3577                        309.20                        350.39
##    ...                           ...                           ...
##    449                          5.65                             0
##    761                          0.00                             0
##   3545                          0.00                             0
##   3124                          4.84                             0
##    798                          0.00                             0
##        MPI000708_204526230010_R07C01 MPI001886_204526230008_R04C01
##                            <numeric>                     <numeric>
##   4102                        392.49                        194.43
##   1431                        728.34                          0.00
##   2274                        500.48                        199.33
##   3688                        899.56                        369.30
##   3577                        345.07                        132.68
##    ...                           ...                           ...
##    449                          0.00                          7.34
##    761                         23.71                         21.40
##   3545                          0.00                          0.00
##   3124                          0.00                          3.67
##    798                          0.00                         13.45
##        MPI003013_204526230010_R06C01 MPI000988_204526230010_R05C02
##                            <numeric>                     <numeric>
##   4102                        337.23                        234.27
##   1431                        676.50                        442.45
##   2274                        468.03                        270.56
##   3688                        913.58                        588.23
##   3577                        296.35                        211.99
##    ...                           ...                           ...
##    449                             0                          8.91
##    761                             0                         11.46
##   3545                             0                          4.46
##   3124                             0                          5.09
##    798                             0                          7.64
##        MPI003472_204526230008_R08C02 MPI003911_204526230008_R10C02
##                            <numeric>                     <numeric>
##   4102                        238.82                        415.19
##   1431                        426.46                        658.43
##   2274                        252.47                        410.99
##   3688                        583.40                        855.54
##   3577                        272.94                        247.43
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001701_204526230010_R03C01 MPI002383_204526230010_R02C02
##                            <numeric>                     <numeric>
##   4102                        145.12                        214.85
##   1431                        179.74                        539.97
##   2274                        149.12                        382.16
##   3688                        210.36                        751.02
##   3577                        109.18                        205.34
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                         15.98                             0
##   3545                         29.29                             0
##   3124                          2.66                             0
##    798                         10.65                             0
##        MPI001766_204526230008_R12C01 MPI002852_204526230008_R05C01
##                            <numeric>                     <numeric>
##   4102                         98.42                        352.90
##   1431                        103.99                        607.84
##   2274                         77.25                        552.79
##   3688                        177.53                        688.11
##   3577                         59.42                        262.02
##    ...                           ...                           ...
##    449                          0.00                          4.42
##    761                          7.43                          0.00
##   3545                          0.00                          0.00
##   3124                         10.77                          3.76
##    798                          7.43                          0.00
##        MPI001263_204526230010_R11C01 MPI003353_204526230010_R07C02
##                            <numeric>                     <numeric>
##   4102                        633.15                        259.67
##   1431                        939.00                        391.74
##   2274                        692.97                        254.42
##   3688                       1049.61                        518.03
##   3577                        446.93                        159.11
##    ...                           ...                           ...
##    449                             0                          6.30
##    761                             0                          5.78
##   3545                             0                         11.82
##   3124                             0                          5.25
##    798                             0                          4.73
##        MPI001667_204526230008_R06C02 MPI002319_204526230008_R02C01
##                            <numeric>                     <numeric>
##   4102                        191.88                        457.31
##   1431                        240.05                        675.83
##   2274                        160.57                        410.00
##   3688                        368.51                        806.49
##   3577                        147.73                        283.85
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                          0.00                             0
##   3545                         28.10                             0
##   3124                          8.83                             0
##    798                          0.00                             0
##        MPI001048_204526230010_R03C02 MPI002095_204526230010_R10C02
##                            <numeric>                     <numeric>
##   4102                        420.97                        154.16
##   1431                        702.03                        242.19
##   2274                        442.39                        171.48
##   3688                        902.43                        292.74
##   3577                        234.43                         85.51
##    ...                           ...                           ...
##    449                          0.00                          2.36
##    761                         17.65                          8.50
##   3545                          0.00                         10.71
##   3124                          0.00                          6.77
##    798                         25.21                         10.39
##        MPI000637_204526230010_R09C01 MPI002418_204526230008_R01C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001701_204526230010_R03C01 MPI003231_204526230010_R12C01
##                            <numeric>                     <numeric>
##   4102                          0.00                             0
##   1431                          0.00                             0
##   2274                          0.00                             0
##   3688                          3.53                             0
##   3577                          0.00                             0
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                          0.00                             0
##   3545                          0.00                             0
##   3124                          8.06                             0
##    798                          0.00                             0
##        MPI001263_204526230010_R11C01 MPI001786_204526230008_R11C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                         39.44
##   3545                             0                         32.87
##   3124                             0                          0.00
##    798                             0                         32.87
##        MPI001946_204526230008_R10C01 MPI000972_204526230010_R10C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                          0.00                             0
##   3545                         39.93                             0
##   3124                          0.00                             0
##    798                         22.82                             0
##        MPI003331_204526230010_R08C01 MPI003520_204526230008_R03C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                         67.02                             0
##   3545                         34.44                             0
##   3124                          0.00                             0
##    798                         30.72                             0
##        MPI000988_204526230010_R05C02 MPI004171_204526230008_R03C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001766_204526230008_R12C01 MPI003353_204526230010_R07C02
##                            <numeric>                     <numeric>
##   4102                             0                          0.00
##   1431                             0                          0.00
##   2274                             0                          0.00
##   3688                             0                         16.74
##   3577                             0                          0.00
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                         47.44
##   3545                             0                         52.09
##   3124                             0                          0.00
##    798                             0                         13.95
##        MPI002319_204526230008_R02C01 MPI001109_204526230010_R04C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                         32.71
##   3545                             0                          7.11
##   3124                             0                          0.00
##    798                             0                         22.76
##        MPI004251_204526230008_R01C01 MPI000708_204526230010_R07C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                          0.00
##    761                          0.00                         64.85
##   3545                         32.09                         45.78
##   3124                          0.00                          0.00
##    798                          0.00                         34.33
##        MPI002095_204526230010_R10C02 MPI002468_204526230010_R01C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI003472_204526230008_R08C02 MPI004054_204526230010_R06C02
##                            <numeric>                     <numeric>
##   4102                             0                          0.00
##   1431                             0                          0.00
##   2274                             0                          0.00
##   3688                             0                          3.64
##   3577                             0                          0.00
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                         74.27
##   3545                             0                         59.70
##   3124                             0                          0.00
##    798                             0                         53.88
##        MPI002802_204526230008_R04C02 MPI003934_204526230008_R12C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI002383_204526230010_R02C02 MPI004215_204526230008_R08C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                          0.00
##   3545                             0                         16.22
##   3124                             0                          0.00
##    798                             0                          0.00
##        MPI001113_204526230008_R07C02 MPI001667_204526230008_R06C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI003013_204526230010_R06C01 MPI001048_204526230010_R03C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                          0.00
##    761                         51.50                         37.36
##   3545                          0.00                         16.01
##   3124                          0.00                          0.00
##    798                         48.98                         28.02
##        MPI001389_204526230008_R06C01 MPI003155_204526230008_R07C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001886_204526230008_R04C01 MPI003787_204526230010_R04C01
##                            <numeric>                     <numeric>
##   4102                          0.00                             0
##   1431                          0.00                             0
##   2274                          7.78                             0
##   3688                         14.26                             0
##   3577                          0.00                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI004246_204526230010_R12C02 MPI002852_204526230008_R05C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                           0.0                             0
##    761                          15.3                             0
##   3545                           0.0                             0
##   3124                           0.0                             0
##    798                           0.0                             0
##        MPI002613_204526230010_R08C02 MPI003911_204526230008_R10C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                             0
##    761                         65.65                             0
##   3545                         38.24                             0
##   3124                          0.00                             0
##    798                         46.53                             0
##        MPI002604_204526230008_R09C02 MPI002533_204526230010_R11C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI001547_204526230008_R05C02 MPI004100_204526230010_R09C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                          0.00
##    761                             0                         49.72
##   3545                             0                         43.98
##   3124                             0                          0.00
##    798                             0                         38.24
##        MPI001386_204526230008_R11C01 MPI003162_204526230008_R02C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI002658_204526230010_R05C01 MPI004198_204526230010_R02C01
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                             0                             0
##    761                             0                             0
##   3545                             0                             0
##   3124                             0                             0
##    798                             0                             0
##        MPI003785_204526230008_R09C01 MPI002088_204526230010_R01C02
##                            <numeric>                     <numeric>
##   4102                             0                             0
##   1431                             0                             0
##   2274                             0                             0
##   3688                             0                             0
##   3577                             0                             0
##    ...                           ...                           ...
##    449                          0.00                          0.00
##    761                         12.30                         55.05
##   3545                         18.16                         27.52
##   3124                          0.00                          4.79
##    798                         12.89                         22.74
##   -------
##   seqinfo: 80 sequences from an unspecified genome; no seqlengths
\end{verbatim}

\begin{itemize}
\tightlist
\item
  ``Conc'' shows the mean read concentration over all the samples (the
  default calculation uses log2 normalized read counts)
\item
  ``Conc\_dex'' - the mean concentration over the samples in dex group
\item
  ``Conc\_veh'' - the mean concentration over the samples in veh group.
\item
  ``Fold'' - the log fold changes (LFCs) between the two groups. A
  positive value indicates increased binding affinity in the DEX group,
  and a negative value indicates increased binding affinity in the VEH
  group.
\end{itemize}

The number of differentially bound sites that have enriched in DEX
samples :

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(dex.report}\OperatorTok{$}\NormalTok{Fold }\OperatorTok{>}\StringTok{ }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1784
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Quantification for edgeR
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{counts.edger <-}\StringTok{ }\NormalTok{dba.dif.anal}\OperatorTok{$}\NormalTok{edgeR}\OperatorTok{$}\NormalTok{DEdata}\OperatorTok{$}\NormalTok{counts}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Peaks annotation
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#  This is the refeernce anno used: /ngs/references/human/GRCh38/Homo_sapiens.GRCh38.97.gtf}
\NormalTok{ref.annot.fn <-}\StringTok{ }\KeywordTok{paste}\NormalTok{(wd, }\StringTok{"Homo_sapiens.GRCh38.97.gtf"}\NormalTok{, }\DataTypeTok{sep =} \StringTok{"/"}\NormalTok{)}

\NormalTok{txDb <-}\StringTok{ }\KeywordTok{makeTxDbFromGFF}\NormalTok{(ref.annot.fn, }\DataTypeTok{format =} \StringTok{"gtf"}\NormalTok{,}
                           \DataTypeTok{organism =} \StringTok{"Homo sapiens"}\NormalTok{,}
                           \DataTypeTok{chrominfo =} \OtherTok{NULL}\NormalTok{,}
                           \DataTypeTok{dbxrefTag =} \StringTok{"gene_id"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Import genomic features from the file as a GRanges object ... OK
## Prepare the 'metadata' data frame ... OK
## Make the TxDb object ...
\end{verbatim}

\begin{verbatim}
## Warning in .get_cds_IDX(mcols0$type, mcols0$phase): The "phase" metadata column contains non-NA values for features of type
##   stop_codon. This information was ignored.
\end{verbatim}

\begin{verbatim}
## OK
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# annotate all peaks}
\NormalTok{dex.anno.report <-}\StringTok{ }\NormalTok{ChIPseeker}\OperatorTok{::}\KeywordTok{annotatePeak}\NormalTok{(dex.report, }\DataTypeTok{tssRegion =} \KeywordTok{c}\NormalTok{(}\OperatorTok{-}\DecValTok{1000}\NormalTok{, }\DecValTok{1000}\NormalTok{), }\DataTypeTok{TxDb=}\NormalTok{txDb, }\DataTypeTok{verbose =} \OtherTok{FALSE}\NormalTok{) }\CommentTok{#, level = "transcript", overlap = "all" }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in .Seqinfo.mergexy(x, y): Each of the 2 combined objects has sequence levels not in the other:
##   - in 'x': GL000008.2, GL000214.1, GL000224.1, KI270303.1, KI270304.1, KI270310.1, KI270311.1, KI270330.1, KI270333.1, KI270336.1, KI270337.1, KI270435.1, KI270438.1, KI270465.1, KI270466.1, KI270467.1, KI270507.1, KI270508.1, KI270509.1, KI270516.1, KI270517.1, KI270518.1, KI270519.1, KI270538.1, KI270544.1, KI270580.1, KI270588.1, KI270589.1, KI270590.1, KI270591.1, KI270709.1, KI270712.1, KI270719.1, KI270723.1, KI270724.1, KI270729.1, KI270732.1, KI270736.1, KI270743.1, KI270751.1, KI270754.1, KI270757.1
##   - in 'y': GL000205.2, GL000213.1, GL000218.1, GL000219.1, KI270721.1, KI270726.1, KI270727.1, KI270731.1, KI270750.1
##   Make sure to always combine/compare objects based on the same reference
##   genome (use suppressWarnings() to suppress this warning).
\end{verbatim}

\begin{verbatim}
## Warning in .Seqinfo.mergexy(x, y): Each of the 2 combined objects has sequence levels not in the other:
##   - in 'x': GL000008.2, GL000214.1, GL000224.1, KI270303.1, KI270304.1, KI270310.1, KI270311.1, KI270330.1, KI270333.1, KI270336.1, KI270337.1, KI270435.1, KI270438.1, KI270465.1, KI270466.1, KI270467.1, KI270507.1, KI270508.1, KI270509.1, KI270516.1, KI270517.1, KI270518.1, KI270519.1, KI270538.1, KI270544.1, KI270580.1, KI270588.1, KI270589.1, KI270590.1, KI270591.1, KI270709.1, KI270712.1, KI270719.1, KI270723.1, KI270724.1, KI270729.1, KI270732.1, KI270736.1, KI270743.1, KI270751.1, KI270754.1, KI270757.1
##   - in 'y': GL000205.2, GL000213.1, GL000218.1, GL000219.1, KI270721.1, KI270726.1, KI270727.1, KI270731.1, KI270750.1
##   Make sure to always combine/compare objects based on the same reference
##   genome (use suppressWarnings() to suppress this warning).

## Warning in .Seqinfo.mergexy(x, y): Each of the 2 combined objects has sequence levels not in the other:
##   - in 'x': GL000008.2, GL000214.1, GL000224.1, KI270303.1, KI270304.1, KI270310.1, KI270311.1, KI270330.1, KI270333.1, KI270336.1, KI270337.1, KI270435.1, KI270438.1, KI270465.1, KI270466.1, KI270467.1, KI270507.1, KI270508.1, KI270509.1, KI270516.1, KI270517.1, KI270518.1, KI270519.1, KI270538.1, KI270544.1, KI270580.1, KI270588.1, KI270589.1, KI270590.1, KI270591.1, KI270709.1, KI270712.1, KI270719.1, KI270723.1, KI270724.1, KI270729.1, KI270732.1, KI270736.1, KI270743.1, KI270751.1, KI270754.1, KI270757.1
##   - in 'y': GL000205.2, GL000213.1, GL000218.1, GL000219.1, KI270721.1, KI270726.1, KI270727.1, KI270731.1, KI270750.1
##   Make sure to always combine/compare objects based on the same reference
##   genome (use suppressWarnings() to suppress this warning).

## Warning in .Seqinfo.mergexy(x, y): Each of the 2 combined objects has sequence levels not in the other:
##   - in 'x': GL000008.2, GL000214.1, GL000224.1, KI270303.1, KI270304.1, KI270310.1, KI270311.1, KI270330.1, KI270333.1, KI270336.1, KI270337.1, KI270435.1, KI270438.1, KI270465.1, KI270466.1, KI270467.1, KI270507.1, KI270508.1, KI270509.1, KI270516.1, KI270517.1, KI270518.1, KI270519.1, KI270538.1, KI270544.1, KI270580.1, KI270588.1, KI270589.1, KI270590.1, KI270591.1, KI270709.1, KI270712.1, KI270719.1, KI270723.1, KI270724.1, KI270729.1, KI270732.1, KI270736.1, KI270743.1, KI270751.1, KI270754.1, KI270757.1
##   - in 'y': GL000205.2, GL000213.1, GL000218.1, GL000219.1, KI270721.1, KI270726.1, KI270727.1, KI270731.1, KI270750.1
##   Make sure to always combine/compare objects based on the same reference
##   genome (use suppressWarnings() to suppress this warning).

## Warning in .Seqinfo.mergexy(x, y): Each of the 2 combined objects has sequence levels not in the other:
##   - in 'x': GL000008.2, GL000214.1, GL000224.1, KI270303.1, KI270304.1, KI270310.1, KI270311.1, KI270330.1, KI270333.1, KI270336.1, KI270337.1, KI270435.1, KI270438.1, KI270465.1, KI270466.1, KI270467.1, KI270507.1, KI270508.1, KI270509.1, KI270516.1, KI270517.1, KI270518.1, KI270519.1, KI270538.1, KI270544.1, KI270580.1, KI270588.1, KI270589.1, KI270590.1, KI270591.1, KI270709.1, KI270712.1, KI270719.1, KI270723.1, KI270724.1, KI270729.1, KI270732.1, KI270736.1, KI270743.1, KI270751.1, KI270754.1, KI270757.1
##   - in 'y': GL000205.2, GL000213.1, GL000218.1, GL000219.1, KI270721.1, KI270726.1, KI270727.1, KI270731.1, KI270750.1
##   Make sure to always combine/compare objects based on the same reference
##   genome (use suppressWarnings() to suppress this warning).
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dex.anno.report}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Annotated peaks generated by ChIPseeker
## 1961/2035  peaks were annotated
## Genomic Annotation Summary:
##              Feature  Frequency
## 9           Promoter 20.7037226
## 4             5' UTR  0.1019888
## 3             3' UTR  2.0397756
## 1           1st Exon  0.2039776
## 7         Other Exon  2.3457420
## 2         1st Intron 18.3069862
## 8       Other Intron 28.5058644
## 6 Downstream (<=300)  1.9887812
## 5  Distal Intergenic 25.8031617
\end{verbatim}

Extract annoted count matrix for RASQUAL

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{annotation.df   <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(dex.anno.report}\OperatorTok{@}\NormalTok{anno)}
\KeywordTok{write.csv2}\NormalTok{(annotation.df, }\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(result.dir.fn, }\StringTok{"dex_deseq_report_annotated.csv"}\NormalTok{))}

\NormalTok{anno.rasqual.df <-}\StringTok{ }\NormalTok{annotation.df[,}\KeywordTok{c}\NormalTok{(}\DecValTok{113}\NormalTok{, }\DecValTok{12}\OperatorTok{:}\DecValTok{106}\NormalTok{)] }\CommentTok{# take only geneID and sampleIDs}
\KeywordTok{write.csv2}\NormalTok{(anno.rasqual.df, }\DataTypeTok{file =} \KeywordTok{paste0}\NormalTok{(result.dir.fn, }\StringTok{"dex_deseq_anno_count_mtrx_for_rasqual.csv"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Plotting
\end{enumerate}

12.1 PCA

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotPCA}\NormalTok{(dba.dif.anal.deseq, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{attributes =}\NormalTok{ DBA_CONDITION, }\DataTypeTok{label =}\NormalTok{ DBA_TREATMENT, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-33-1.pdf}
12.2. Volcano

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotVolcano}\NormalTok{(dba.dif.anal.deseq, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-34-1.pdf}
12.3. Boxplot

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dba.plotBox}\NormalTok{(dba.dif.anal.deseq, }\DataTypeTok{method =}\NormalTok{ DBA_DESEQ2, }\DataTypeTok{contrast =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{allele_spec_chpseq_analysis_files/figure-latex/unnamed-chunk-35-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Export results
\end{enumerate}

Write BED files for each set of significant regions identified by edgeR,
separating them based on the gain or loss of enrichment.

\end{document}
